### ISSUE TITLE
Create a Community flag

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#1062]
### Discussed in https://github.com/micronaut-projects/micronaut-starter/discussions/983

<div type='discussions-op-text'>

<sup>Originally posted by **sdelamo** November 25, 2021</sup>
I would like to include a flag in features to flag them as `community`.  E.g Camunda related features or [Micronaut Agorapulse libraries](https://github.com/agorapulse/micronaut-aws-sdk).  Similar to the `preview` flag.

thoughts? 
</div>

**Comment by timyates** [comment]
@sdelamo How would we use this to flag the Agorapulse libraries?  Do they show up in the micronaut-starter project somewhere?

**Comment by sdelamo** [comment]
For preview features what we do is they are suffixed with `[PREVIEW]`. 

https://github.com/micronaut-projects/micronaut-starter/blob/3.3.x/starter-cli/src/main/java/io/micronaut/starter/cli/command/ListFeatures.java#L94-L96

We could do the same but with `[COMMUNITY]`. Something simple to start with.

**Comment by sdelamo** [comment]
I would probably create an enum called mantainer: 

```
enum Maintainer {
FOUNDATION, 
COMMUNITY
}
```

and a defaullt method in `Feature`

```
default getMaintainer {
    return Maintainer.FOUNDATION;
}
```

If it is `COMMUNITY` we can display a suffix in the title. 

That is is just an idea for the API.

**Comment by timyates** [comment]
Good idea, I'd gone with a Boolean but this makes more sense 👍
