### ISSUE TITLE
Feature for Micronaut Data MongoDB

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#1085]

**Comment by timyates** [comment]
Already exists

![image](https://user-images.githubusercontent.com/49317/157440082-7e8cefae-0204-4240-9a9c-82369e8eed48.png)

https://github.com/micronaut-projects/micronaut-starter/blob/3.3.x/starter-core/src/main/java/io/micronaut/starter/feature/database/DataMongo.java

**Comment by sdelamo** [comment]
The Micronaut documentation link is incorrect: 

```
        return "https://micronaut-projects.github.io/micronaut-data/3.3.x/guide/#mongo";
```

I think it would be test to pointing to snapshot for now.

**Comment by timyates** [comment]
That URL works and currently points to the RC1 documentation.  I assume when 3.3.0 is released it will also point to the correct documentation.  Is the snapshot docs better?

**Comment by sdelamo** [comment]
Ideally, we link to `latest` but Micronaut Data Mongo DB section docs is not yet in latest. Thus, `snapshot` is better. Because, at least it would be relevant when 3.4.0 is released and it will contain any improvements to the docs.
