### ISSUE TITLE
data-mongodb feature contributes mongo-sync as implementation but it should be runtime according to the data documentation

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#1168]
> <img width="817" alt="Screenshot 2022-04-07 at 13 26 13" src="https://user-images.githubusercontent.com/864788/162188618-b5668a02-9e81-432d-b983-375a384938e3.png">

https://micronaut-projects.github.io/micronaut-data/latest/guide/#mongo

> And include MongoDB Sync driver:

> runtime("org.mongodb:mongodb-driver-sync")

**Comment by timyates** [comment]
Done in https://github.com/micronaut-projects/micronaut-starter/pull/1155
