### ISSUE TITLE
select correct runtime for gradle and labmda

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#1206]
Since Micronaut Gradle plugin 3.4.0 we support now two runtimes for Lambda. If you are deploying your Lambda functions to a Java runtime use the environment `lambda_java`. If you deploy a GraalVM Native Image of your Micronaut Function to a Lambda Provided runtime use the environment `lambda_provided`. 

We should select the appropriate runtimes when the user selects `aws-lambda` or if the users selects `aws-lambda` + `graalvm`. features.

**Comment by timyates** [comment]
How does this differ from https://github.com/micronaut-projects/micronaut-starter/issues/1160 ?
