### ISSUE TITLE
mn bash script doesn't work

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-starter#121]
Running the `mn` bash script doesn't start the cli.

- `./gradlew starter-cli:clean starter-cli:assemble`
- `cd starter-cli/build/bin`
- `./mn`

```
Error: Could not find or load main class io.micronaut.starter.cli.MicronautStarter
```

Debugging the script, it tries to run the following:

```
java -classpath /home/ivan/workspaces/micronaut/micronaut-starter/starter-cli/build/starter-cli-1.0.0.BUILD-SNAPSHOT-all.jar io.micronaut.starter.cli.MicronautStarter
```

The problem is that the file `starter-cli-1.0.0.BUILD-SNAPSHOT-all.jar` is not in the `build` directory but in `build/libs`. If I copy that file manually from `build/libs` to `build` it works as expected.

In the old cli in `1.3.x` branch we copied that file in the `fatJar` task, but now we're using `shadowJar` instead so not really sure if that's the way to solve this now.

This is the output of the installed 2.0.0.M2 with the jar file in the `bin` parent directory:

![image](https://user-images.githubusercontent.com/559192/80089277-f3fb3200-855d-11ea-9f88-973370d62002.png)

**Comment by graemerocher** [comment]
I don't think this is a valid issue. The following works:

```
./gradlew starter-cli:cliZip
unzip starter-cli/build/distributions/micronaut-cli-1.0.0.BUILD-SNAPSHOT.zip -d tmp
cd tmp/bin
./mn
```

**Comment by ilopmar** [comment]
You are right, my bad.
