### ISSUE TITLE
Task 'buildNativeLambda' not found. Works with `-Pmicronaut.runtime=lambda_provided`

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#1276]
### Expected Behavior

In a multi project build, I expected to be able to run:

`./gradlew :app:buildNativeLambda`

It works if I do: 

`./gradlew :app:buildNativeLambda -Pmicronaut.runtime=lambda_provided`

### Actual Behaviour

```
./gradlew :app:buildNativeLambda                                     

FAILURE: Build failed with an exception.

* What went wrong:
Task 'buildNativeLambda' not found in project ':app'.

* Try:
> Run gradlew tasks to get a list of available tasks.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

```

### Steps To Reproduce

Clone: 

https://github.com/grails-core-issues-forks/micronaut-gradle-plugin-buildNativeLambda

Run `./gradlew :app:buildNativeLambda`

If you run `./gradlew :app:buildNativeLambda -Pmicronaut.runtime=lambda_provided `it works. 

### Example Application

https://github.com/grails-core-issues-forks/micronaut-gradle-plugin-buildNativeLambda

### Version

3.5.0-SNAPSHOT

**Comment by sdelamo** [comment]
@melix this is the issue we discussed yesterday.

**Comment by melix** [comment]
So this isn't a bug in the plugin. While the build script says `runtime("lambda_provided")`, the `gradle.properties` file declares:

`micronaut.runtime=lambda_java`

So it takes precedence.

**Comment by sdelamo** [comment]
should we remove `micronaut.runtime` from `gradle.properites` in launch/cli? We use a string instead of the property: 

<img width="721" alt="Screenshot 2022-05-31 at 11 05 36" src="https://user-images.githubusercontent.com/864788/171136705-70d21297-920d-425c-9765-f6f44164e76a.png">

**Comment by melix** [comment]
Obviously we should remove it from `gradle.properties`, yes, since it conflicts (and takes precedence) with whatever is declared in the DSL.

**Comment by sdelamo** [comment]
I have moved this to starter instead of closing it.
