### ISSUE TITLE
Add feature which generate Cloud Build Configuration file

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#1281]
See: https://github.com/micronaut-projects/micronaut-starter/issues/1280

See: https://cloud.google.com/build

**Comment by wetted** [comment]
Examples are here: https://github.com/GoogleCloudPlatform/cloud-build-samples

**Comment by sdelamo** [comment]
something like this probably https://github.com/GoogleCloudPlatform/cloud-build-samples/blob/main/gradle-example/cloudbuild.yaml#L20-L22

**Comment by wetted** [comment]
> something like this probably https://github.com/GoogleCloudPlatform/cloud-build-samples/blob/main/gradle-example/cloudbuild.yaml#L20-L22

Yeah, that's what I was planning to use, and the Maven counterpart.

**Comment by sdelamo** [comment]
We have to to use the appropriate commit messages to close issues: 

https://github.blog/2013-01-22-closing-issues-via-commit-messages/
