### ISSUE TITLE
Create Hibernate Reactive Feature

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#1306]
https://micronaut-projects.github.io/micronaut-sql/snapshot/guide/index.html#_hibernate_reactive

I assume we should do the second option. 

> other option is to include one of the existing Micronaut SQL support libraries

**Comment by sdelamo** [comment]
> https://micronaut-projects.github.io/micronaut-sql/snapshot/guide/index.html#_hibernate_reactive
> 
> I assume we should do the second option.

@dstepanov thoughts 👆 ?

**Comment by dstepanov** [comment]
I would use the first option, just like Hibernate Reactive documents it. Otherwise, we cannot have multiple data sources and some of the drivers. And it's easier for test resources to support.

I have found the second option was producing failing tests only on CI, I need to investigate.
