### ISSUE TITLE
Create Ksuid feature

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-starter#1308]
The DynamoDB guide requires a ksuid feature

https://github.com/micronaut-projects/micronaut-guides/pull/996

Currently for the guide it is a locally defined feature, but for the guide to work outside of guides, it will need to be in here

**Comment by sdelamo** [comment]
I am not sure we need this as a feature in starter. We have several guides which use "guides-only" features.

**Comment by timyates** [comment]
Cool, It was a placeholder incase I was right in the Dynamodb guide review

TLDR: I was wrong 😀
