### ISSUE TITLE
Missing dependency when create data hibernate reactive maven project

### ISSUE THREAD

**Issue by romannaglic** [micronaut-projects/micronaut-starter#1362]
Missing dependency in pom.xml file generated by Micronaut Launch

Create a project (Java Version 11) with the following features:

- Micronaut version: 3.6.0
- Language: Kotlin
- Build Tool: Maven
- hibernate-reactive-jpa
- mysql
- vertx-mysql-client

Compiling the generated project throws an error:

![image](https://user-images.githubusercontent.com/14903499/184318251-d3dee42b-5085-4e8e-8828-82af7e6dd7a1.png)

The reason for that error is a missing dependency in pom.xml in kotlin-maven-plugin.

If you add 
```
<dependency>
    <groupId>org.jetbrains.kotlin</groupId>
    <artifactId>kotlin-maven-noarg</artifactId>
    <version>${kotlinVersion}</version>
</dependency>
```

projects compile successfully.

**Comment by timyates** [comment]
This relates to the failure seen here https://github.com/micronaut-projects/micronaut-guides/pull/1048
