### ISSUE TITLE
Unclear docs for starter-web-netty

### ISSUE THREAD

**Issue by benmccann** [micronaut-projects/micronaut-starter#141]
https://micronaut-projects.github.io/micronaut-starter/snapshot/guide/ says "The subproject starter-web-netty provides an implementation that runs on Netty"

Isn't this the default? micronaut.io says "NON-BLOCKING HTTP SERVER BUILT ON NETTY" on the homepage. What does this starter do exactly?

**Comment by graemerocher** [comment]
This is an unannounced and unreleased project so what it does will be revealed. 

As for the Netty implemetation, Micronaut runs on more than just Netty nowdays with support for Serverless and Servlet containers
