### ISSUE TITLE
UI: In light mode selected features are barely visible

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-starter#143]
Wasn't such an issue on a high res display but on a older MacBook Air could barely see this text:

<img width="353" alt="Screenshot 2020-04-28 at 10 37 18" src="https://user-images.githubusercontent.com/66626/80466033-419be400-893c-11ea-875a-4e68bc4acc70.png">

**Comment by jameskleeh** [comment]
The title should be white

**Comment by eahrold** [comment]
Addressed in https://github.com/micronaut-projects/static-website/pull/37
