### ISSUE TITLE
Create a Chocolatey package

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-starter#146]
[Chocolatey](https://chocolatey.org/) is a package manager for Windows.

This issue is to see if there are users interested in it.

Documentation: https://chocolatey.org/docs/create-packages

**Comment by aadrian** [comment]
@alvarosanchez however many Choco package definitions force upon users new/different JDKs, and don't correctly check if the user already has a valid `JAVA_HOME" set.

**Comment by graemerocher** [comment]
We build a native windows executable now so no JDK is needed
