### ISSUE TITLE
Unable to build Native Image of CLI

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#1469]
Checkout branch `interactive-prompt`

Run

```
sdk use java 22.2.r11-grl
./gradlew micronaut-cli:build       
native-image --no-fallback -cp starter-cli/build/libs/micronaut-cli-*-all.jar
```

it fails with: 
```
Fatal error: java.lang.IllegalAccessError: class io.micronaut.buffer.netty.NettyFeature (in unnamed module @0x33eb0d4) cannot access class com.oracle.svm.core.jdk.SystemPropertiesSupport (in module org.graalvm.nativeimage.builder) because module org.graalvm.nativeimage.builder does not export com.oracle.svm.core.jdk to unnamed module @0x33eb0d4
	at io.micronaut.buffer.netty.NettyFeature.beforeAnalysis(NettyFeature.java:66)
```

See: 

https://github.com/micronaut-projects/micronaut-core/blob/3.7.x/buffer-netty/src/main/java/io/micronaut/buffer/netty/NettyFeature.java#L66

Any idea @yawkat  ?

**Comment by timyates** [comment]
If we change `starter-cli/src/main/resources/META-INF/native-image/io.micronaut.starter.cli/micronaut-starter-cli/native-image.properties` to:

```
Args = -H:Name=mn \
       -H:Class=io.micronaut.starter.cli.MicronautStarter \
        --initialize-at-build-time=picocli.CommandLine$Help$Ansi
```

And add the export to the `native-image` command:

```
native-image --add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk=ALL-UNNAMED --no-fallback -cp starter-cli/build/libs/micronaut-cli-*-all.jar
```

Then  it works, but I have no idea why we need this change...

**Comment by alvarosanchez** [comment]
Looks to me like https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/507

But it's strange since that PR was shipped in 3.5.1 and starter is already using 3.6.2 🤔

**Comment by melix** [comment]
I was confused, because I thought you were using the Gradle plugin to build the native image, but you are _not_: you are using `native-image` from CLI, so it's normal that you have to add the `--add-exports` which the Gradle plugin does by default.

**Comment by alvarosanchez** [comment]
🤯 

I missed that part too

**Comment by sdelamo** [comment]
I no longer know if it applies.
