### ISSUE TITLE
Add jOOQ formula

### ISSUE THREAD

**Issue by benmccann** [micronaut-projects/micronaut-starter#151]
Wow I just found https://micronaut.io/start/ and can I say it's the coolest thing ever?! Way to go to the whole team that worked on this!

I'd love to see a formula for [Micronaut's jOOQ support](https://micronaut-projects.github.io/micronaut-sql/latest/guide/#jooq).

CC @lightoze @lukaseder as other people who might be interested in this

I may try to add it if I get time to figure out how. There isn't a guide on a adding a new formula by chance is there?

It looks like it maybe would go here:
* https://github.com/micronaut-projects/micronaut-starter/tree/master/starter-core/src/main/java/io/micronaut/starter/feature/database

**Comment by graemerocher** [comment]
Yes that is right. We are still testing and plan to go live officially on Thursday. Thanks for the feedback!

**Comment by lukaseder** [comment]
> CC @lightoze @lukaseder as other people who might be interested in this

Well, I definitely *am* interested in this! :-)
