### ISSUE TITLE
Create feature for websockets

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#1511]
4.0.x branch

It should add `io.micronaut:micronaut-websocket`. 

> `io.micronaut:micronaut-http-server` no longer exposes `micrnoaut-websocket` transitively. If your application uses annotations such as ann:websocket.annotation.ServerWebSocket[], add the `micronaut-websocket` dependency to your application classpath:

see: https://github.com/micronaut-projects/micronaut-core/pull/8235

**Comment by wetted** [comment]
https://github.com/micronaut-projects/micronaut-starter/pull/1623 doesn't close this.

This is really for Micronaut 4. Once the 4.0.x branch is ready and it gets merged up, then `Websocket.isVisble()` should be changed to no longer return false, and the test for it in `WebsocketSpec` should remove the `@PendngFeature` annotation.
