### ISSUE TITLE
Organization suggestions

### ISSUE THREAD

**Issue by benmccann** [micronaut-projects/micronaut-starter#152]
[The Cassandra test](https://github.com/micronaut-projects/micronaut-starter/tree/master/starter-core/src/test/groovy/io/micronaut/starter/feature/cassandra) isn't under database like [the feature is](https://github.com/micronaut-projects/micronaut-starter/blob/master/starter-core/src/main/java/io/micronaut/starter/feature/database/Cassandra.java)

Should `vertx` (reactive database drivers) go under `database`? `redis` as well (though with `redis` there's also some argument for `cache` but `database` seems a better fit to me. I wonder if we'll run into confusing with others that fit multiple categories)?

I won't have time to send a PR for this one, but thought I'd share since I noticed this while working on the jooq formula

**Comment by jameskleeh** [comment]
Redis and vertx are in the database category. Perhaps that changed since you created this issue

**Comment by benmccann** [comment]
To clarify, I mean the code directory path and not the category

Thanks for all the fixes and improvements!
