### ISSUE TITLE
UI: placeholder text colour is too strong

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-starter#157]
In dark mode, the placeholder text to search features looks like if the field is pre-filled:

![image](https://user-images.githubusercontent.com/153880/80565887-e6c4c400-89f1-11ea-9b7c-7057cc144161.png)

It's even brighter than the label.

In light mode it is much better:

![image](https://user-images.githubusercontent.com/153880/80565944-11168180-89f2-11ea-8cb9-44fc7d6f28e7.png)

**Comment by eahrold** [comment]
Addressed in https://github.com/micronaut-projects/static-website/pull/46/commits
Commit https://github.com/micronaut-projects/static-website/pull/46/commits/3aa7018694b93ad951b9db204a78df6ddb33e8c7
