### ISSUE TITLE
Add feature for Micronaut Data Cosmos 

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#1573]
see: https://micronaut-projects.github.io/micronaut-data/latest/guide/#azureCosmos

**Comment by radovanradic** [comment]
@sdelamo I added initial commit for this earlier https://github.com/micronaut-projects/micronaut-starter/commit/f7eb5e5bb284b834ecaeed1c797301ecd9744cb9 but we might need test-resource support first?
https://github.com/micronaut-projects/micronaut-test-resources/issues/140

**Comment by sdelamo** [comment]
I think we can add the feature and later when test-resource is there improve it. 

Can you submit a PR @radovanradic ? I assume that commit is in a branch which was not yet PRed

**Comment by radovanradic** [comment]
@sdelamo I have created PR https://github.com/micronaut-projects/micronaut-starter/pull/1584
