### ISSUE TITLE
Serialization and Lambda features are incompatible

### ISSUE THREAD

**Issue by mattthebig** [micronaut-projects/micronaut-starter#1579]
### Description

There is an apparent problem with projects created with Serialization and AWS Lambda support (and maybe Spock)

### Steps to Reproduce

1. curl --location --request GET 'https://launch.micronaut.io/create/default/matt.togethar.demo?lang=JAVA&build=GRADLE&test=SPOCK&javaVersion=JDK_17&features=aws-lambda&features=aws-lambda-custom-runtime&features=graalvm&features=aws-v2-sdk&features=serialization-jackson' --output demo.zip
2. unzip demo.zip
3. cd demo
4. ./gradlew build

### Expected Behaviour
Build succeeds

### Actual Behaviour
Build fails

> \> Task :test
> 
> HomeControllerSpec > initializationError FAILED
>     java.lang.NoClassDefFoundError at HomeControllerSpec.groovy:16
>         Caused by: java.lang.ClassNotFoundException at HomeControllerSpec.groovy:16
> 
> 1 test completed, 1 failed
> 
> \> Task :test FAILED

### Environment Information
- **Operating System**: Windows
- **Micronaut Version:** 3.8
- **JDK Version:** 19

**Comment by mattthebig** [comment]
FYI: This issue can be fixed by /all/implementation/ but I'm hardly confident that won't break something else

configurations.all {
    resolutionStrategy.dependencySubstitution {
        substitute(module("io.micronaut:micronaut-jackson-databind"))
            .using(module("io.micronaut.serde:micronaut-serde-jackson:1.5.0"))
    }
}

**Comment by wetted** [comment]
The `micronaut-serde` build configuration is a problem, since it hides `io.micronaut:micronaut-jackson-databind`

```
configurations.all {
    resolutionStrategy.dependencySubstitution {
        substitute(module("io.micronaut:micronaut-jackson-databind"))
            .using(module("io.micronaut.serde:micronaut-serde-jackson:1.5.0"))
    }
}
```

However, `MicronautLambdaContainerHandler` needs `io.micronaut.jackson.codec.JsonMediaTypeCodec` from a transitive dependency of `micronaut-jackson-databind` -> `micronaut-jackson-core` -> `micronaut-json-core`.

```
    protected void initContainerState() {
        this.lambdaContainerEnvironment.setApplicationContext(applicationContext);
        this.lambdaContainerEnvironment.setJsonCodec(applicationContext.getBean(JsonMediaTypeCodec.class));

```

Adding `testRuntimeOnly("io.micronaut:micronaut-json-core")` to the build doesn't help. I guess what puzzles me is that `micronaut-json-core` is a transitive of `micronaut-serde-jackson`.

Any thoughts about this @sdelamo ? Is `micronaut-aws` just not compatible and needs to be changed?

**Comment by wetted** [comment]
I cobbled together a version of this starter project, but using latest Micronaut 4 SNAPSHOT and Milestone versions. See https://github.com/wetted/aws-serde-starter-demo

That seems to work fine.  Using the Micronaut 3 starter version described by this issue, I can only build successfully by removing the dependency substitution for jackson-databind in the configuration resolution strategy of the build. This is related to the [documentation for micronaut-serde](https://micronaut-projects.github.io/micronaut-serialization/latest/guide/#jacksonQuick) that warns excluding Jackson Databind might not be an option.

@sdelamo What would you like to do further on this, if anything.

**Comment by wetted** [comment]
This works in Micronuat 4. https://github.com/wetted/aws-serde-starter-demo
