### ISSUE TITLE
Consider using Maven 3.9.0 in maven applications generated with Micronaut CLI/Launch

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#1606]
https://maven.apache.org/docs/3.9.0/release-notes.html

**Comment by wetted** [comment]
Known Issues
Observed roughly 10% slow-down on large builds when compared to Maven 3.8.7, tracked on [MNG-7677](https://issues.apache.org/jira/browse/MNG-7677).

🤔
