### ISSUE TITLE
Upgrade Gradle Plugin to 3.7.3

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#1626]
https://github.com/micronaut-projects/micronaut-starter/pull/1613

see: https://github.com/micronaut-projects/micronaut-gradle-plugin/releases/tag/v3.7.3

**Comment by sdelamo** [comment]
@melix I have assigned this to @wetted Not sure if you are already working on it.

**Comment by melix** [comment]
I am not
