### ISSUE TITLE
Add `micronaut-aop` feature

### ISSUE THREAD

**Issue by nbrugger-tgm** [micronaut-projects/micronaut-starter#1633]
At the moment the only way to find the name of the `io.micronaut:micronaut-aop` dependency and the scope it should be used in (`compileOnly` for gradle) is reading a [blogpost(micronaut.io)](https://micronaut.io/2019/10/07/micronaut-aop-awesome-flexibility-without-the-complexity/) - no documentation. I think adding it to launch is a great way to show people this amazing feature. An alternative would be to add it to  add it to the almighty micronaut documentation page : https://docs.micronaut.io/latest/guide/#aop

**Comment by sdelamo** [comment]
Good idea @nbrugger-tgm
