### ISSUE TITLE
Consider reworking internal `pom.xml`

### ISSUE THREAD

**Issue by melix** [micronaut-projects/micronaut-starter#1635]
We use a [checked-in pom.xml](https://github.com/micronaut-projects/micronaut-starter/blob/be9d26ab723d39010b483822daed91d1d88bf1ec/starter-core/src/main/resources/pom.xml) file to handle dependency coordinates of dependencies which are added by the project generator.

This file is static, and uses the `pom.xml` format so that dependabot can update dependencies automatically.

In practice, it is quite cumbersome to use. Especially, any Gradle plugin update requires modifying [3 files](https://github.com/micronaut-projects/micronaut-starter/pull/1631) and, as far as I understand, we can't even use properties in that pom because they would not be recognized by [our custom parsing logic](https://github.com/micronaut-projects/micronaut-starter/blob/414d81590cbc80d76d6b111e7273bd7eda8695f8/starter-core/src/main/java/io/micronaut/starter/build/dependencies/CoordinatesUtils.java#L38).

Instead, I suggest we use a similar approach to what we have in other projects, which is to use a version catalog, updated via Renovatebot, which is then used to generate code constants.

**Comment by melix** [comment]
I have a prototype for this which is currently blocked by the Rocker plugin which brings a conflicting version of ANTLR than the one used to parse TOML files :/

**Comment by sdelamo** [comment]
can we close this @melix  ?

**Comment by melix** [comment]
yup
