### ISSUE TITLE
Generated projects with `google-cloud-function-http` feature include no-longer-needed dependencies

### ISSUE THREAD

**Issue by jon-signal** [micronaut-projects/micronaut-starter#1681]
The project template generated when a project includes the `google-cloud-function-http` feature includes the following comment:

https://github.com/micronaut-projects/micronaut-starter/blob/5a81642955e30defcb5f7c602f3b93e4fd1e7a1b/starter-core/src/main/java/io/micronaut/starter/feature/build/maven/templates/pom.rocker.raw#L104

https://github.com/GoogleCloudPlatform/functions-framework-java/pull/32 has long since been merged and I think the additional dependencies can be removed. I'd be happy to open a pull request, but it's not entirely clear to me which of the dependencies (just the dependency following the comment? all of the dependencies following the comment?) are affected.

**Comment by wetted** [comment]
@jon-signal I am addressing this as part of a larger rocker template refactor on #1707 . Thank you.
