### ISSUE TITLE
Micronaut Validation should add an annotation processor and a dependency

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#1698]
https://micronaut-projects.github.io/micronaut-validation/snapshot/guide/#quickStart

New Group id is `io.micronaut.validation`

For maven, as we do with Micronaut Data, we will need to set a property `micronaut.validation.version`. 

ping @alvarosanchez

**Comment by sdelamo** [comment]
@wetted To start, We should move the logic of adding the dependencies outside of rocker into Java classes. If you want create such a PR and target 3.9.x

**Comment by alvarosanchez** [comment]
We don't need to set the `micronaut.validation.version` property in user POMs, it's inherited from the Platform BOM. The same applies to `micronaut.data.version`, don't know why it's there
