### ISSUE TITLE
Update Starter to reflect the changes in Micronaut Maven Plugin 4.x

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-starter#1712]
- New group id: `io.micronaut.maven`.
- Should add `org.apache.maven.plugins:maven-enforcer-plugin` by default

**Comment by sdelamo** [comment]
@alvarosanchez I am working on the starter 4.0.x build. I am going to assign this to myself and ask you for help if needed.

**Comment by alvarosanchez** [comment]
Closed via #1723

**Comment by alvarosanchez** [comment]
@sdelamo I don't see the enforcer plugin being added in the deployed version of Launch v4, but it's strange, I do see it in #1723. Do you know what happened?
