### ISSUE TITLE
Spring Boot/Web Features should apply Spring Feature

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-starter#174]
Currently they only apply themselves

**Comment by ilopmar** [comment]
@graemerocher does the same applies for #166 (Spring Data JPA) and #170 (Spring Data JDBC)?

**Comment by graemerocher** [comment]
Yes

**Comment by ilopmar** [comment]
Fixed in https://github.com/micronaut-projects/micronaut-starter/commit/96f44767ed3262f7d29e937ad74dcbddec0eb324
