### ISSUE TITLE
Apply exclusions to the Micronaut OpenAPI annotation processor

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-starter#1747]
```xml
<path>
  <groupId>io.micronaut.openapi</groupId>
  <artifactId>micronaut-openapi</artifactId>
  <version>${micronaut.openapi.version}</version>
  <exclusions>
    <exclusion>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-inject</artifactId>
    </exclusion>
  </exclusions>
</path>
```

**Comment by sdelamo** [comment]
@wetted see validation feature for an example. 

I think we should probably create a method in `MicronautDependencyUtils` 

which is something like: 

```java
Dependency micronautModuleMavenannotationProcessor(String groupId, String artifactId, String propertyName)
```

and call it from validation, openapi, data features.

**Comment by wetted** [comment]
@alvarosanchez @sdelamo 
Is it the case that for all Maven annotationProcessors, the `micronaut-inject` exclusion should be present?

for example:
- micronaut-http-validation
- picocli-codegen
- lombok

Or is it just the ones that are Micronaut module processors?

**Comment by sdelamo** [comment]
picocli-gen and Lombok don't depend on Micronaut-inject. Hence the exclusion should not be present for those. 

micronaut-http-validation is in micronaut-core repository. Thus, it is aligned with core Micronaut-inject. Hence, the exclusion is not necessary.

**Comment by wetted** [comment]
Thanks @Sergio. I was trying to generalize this enough to support testing it with `MavenBuildTestVerifier.hasAnnotationProcessor()` without changing the API.

Meanwhile I'm changing test for all the features I touch  all the features I touch to use BuildVerifier.
