### ISSUE TITLE
Add space spacing to the top of the UI

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-starter#176]
Logo is currently bumped right up against the top, with the feature list gone it means there is a lot of space now. I think we should add a little space above the logo:]

<img width="1430" alt="Screenshot 2020-04-29 at 14 34 54" src="https://user-images.githubusercontent.com/66626/80596450-aa5f8b00-8a26-11ea-92c8-ac9e90abfd2e.png">

**Comment by eahrold** [comment]
Addressed in. PR https://github.com/micronaut-projects/static-website/pull/46/files

Commit https://github.com/micronaut-projects/static-website/pull/46/commits/5d0738bd2cb46c7670fed977423dca680c3ece37
