### ISSUE TITLE
Consider Feature::supports(Language language)

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#181]
I think we should create a method to flag features only supported by a particular language. 

We are currently doing `exclude. to do it. 

```
@Override
    public void processSelectedFeatures(FeatureContext featureContext) {
        if (featureContext.getLanguage() != Language.KOTLIN) {
            featureContext.exclude(new FeaturePredicate() {
                @Override
                public boolean test(Feature feature) {
                    return feature instanceof KotlinExtensionFunctions;
                }

                @Override
                public Optional<String> getWarning() {
                    return Optional.of("Kotlin Extension Functions feature only supports Kotlin");
                }
            });
        }
    }
```

We are currently using this in `KotlinExtensionFunctions`, `Ktor` or in `GraalNativeImage` where we disable groovy. 

I think it would look nicer to have 

`boolean supports(Language language)` at `Feature`. 

If don't know if with the exclude approach, we can support an API endpoint which for example  retrieves only  features supported by Groovy.

**Comment by jameskleeh** [comment]
These features should probably implement LanguageSpecificFeature which when used would change the default language and throw an error when attempted to be used with an incompatible language. We don't need another API as it already exists

**Comment by jameskleeh** [comment]
> If don't know if with the exclude approach, we can support an API endpoint which for example retrieves only features supported by Groovy.

`create-app --lang groovy --list-features`
