### ISSUE TITLE
Hibernate GORM is missing

### ISSUE THREAD

**Issue by hantsy** [micronaut-projects/micronaut-starter#1858]
### Description

Upgraded my example project to 4.0.0-M3, the `io.micronaut.groovy:micronaut-hibernate-gorm` is missing and can not resolved.

### Environment Information

- **Operating System**: Windows 10 Pro
- **Micronaut Version:**  4.0.0-M3
- **JDK Version:** 17

### Example Application
https://github.com/hantsy/micronaut-sandbox/tree/master/hibernate-gorm

**Comment by sdelamo** [comment]
@hantsy GORM currently does not support Groovy 4 which is the baseline for Micronaut Framework 4. Thus, Micronaut Framework 4 does not support GORM yet.

**Comment by tobiaskraft** [comment]
@sdelamo : Grails 7 is now available and runs on Groovy 4. Are there any plans to make Hibernate GORM again available in Micronaut.
