### ISSUE TITLE
Micronaut framework 4  Maven application still use micronaut runtime

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#1883]
Micronaut Maven applications still include micronaut-runtime: 

```
<dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-runtime</artifactId>
      <scope>compile</scope>
      <exclusions>
          <exclusion>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-jackson-databind</artifactId>
          </exclusion>
        </exclusions>
    </dependency>
```

Since Micronaut Framework 4, micronaut-runtime is just an umbrella of other dependencies. It will probably be removed in Micronaut Framework 5. Which [dependencies](https://github.com/micronaut-projects/micronaut-core/blob/4.0.x/runtime/build.gradle#L8-L15) should we add instead of runtime?

**Comment by sdelamo** [comment]
Thoughts @graemerocher @alvarosanchez ? What do we do in the gradle plugin @melix ?

**Comment by alvarosanchez** [comment]
There shouldn't be a difference in dependencies between Maven and Gradle builds

**Comment by melix** [comment]
As far as I can tell the only `runtime` dependency which is added by the Gradle plugin is:

```java
// added to ensure file watch works more efficiently on OS X
        if (Os.isFamily(Os.FAMILY_MAC)) {
            developmentOnly.getDependencies().add(project.getDependencies().create("io.micronaut:micronaut-runtime-osx"));
        }
```

**Comment by graemerocher** [comment]
Maven plugin shouldn't directly depend on `micronaut-runtime` no, this is a bug
