### ISSUE TITLE
For docker files match version of selected JDK

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#189]
See: 

https://github.com/micronaut-projects/micronaut-starter/blob/master/starter-core/src/main/java/io/micronaut/starter/feature/graalvm/template/dockerfile.rocker.raw#L8-L10

https://github.com/micronaut-projects/micronaut-starter/blob/master/starter-core/src/main/java/io/micronaut/starter/feature/graalvm/template/lambdadockerfile.rocker.raw#L29

there should be test for this change.

Here we use `openjdk:14-alipine` not sure if this needs to change: 

https://github.com/micronaut-projects/micronaut-starter/blob/master/starter-core/src/main/java/io/micronaut/starter/feature/other/template/dockerfile.rocker.raw#L8

**Comment by graemerocher** [comment]
See explanation in #190
