### ISSUE TITLE
Micronaut Application with azure-function feature generates invalid FunctionTest for 4.0.0

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-starter#1890]
When we generate a Micronaut Application with the `azure-function` feature, the generated test is

```
    public void testFunction() throws Exception {
        try (Function function = new Function()) {
            HttpRequestMessageBuilder.AzureHttpResponseMessage response =
                function.request(HttpMethod.GET, "/demo")
                        .invoke();

            assertEquals(HttpStatus.OK, response.getStatus());
        }
    }
```

However, `HttpRequestMessageBuilder.AzureHttpResponseMessage` [was removed in the update to 4.0.0](https://github.com/micronaut-projects/micronaut-azure/pull/398), so this code no longer compiles

**Comment by sdelamo** [comment]
I think this was closed via https://github.com/micronaut-projects/micronaut-starter/pull/1917/files
