### ISSUE TITLE
Use standard jdk image for docker file used to generate native image 

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#190]
https://github.com/micronaut-projects/micronaut-starter/blob/master/starter-core/src/main/java/io/micronaut/starter/feature/graalvm/template/lambdadockerfile.rocker.raw#L9-L13

> Is a gradle or maven specific image required here? Can't we just use ./mvnw ./gradlew
> A standard jdk image like opendjk-12:alpine should be used instead

**Comment by graemerocher** [comment]
Many older JDKs don't support Docker memory options correctly hence why we use JDK 14 which has built in support for running on Docker and also provides the best startup time

**Comment by jameskleeh** [comment]
@graemerocher This isn't isn't in reference to using JDK14

**Comment by alvarosanchez** [comment]
Fixed via #546
