### ISSUE TITLE
Micronaut fails to start when installed via sdkman on apple silicon

### ISSUE THREAD

**Issue by brucej72** [micronaut-projects/micronaut-starter#1919]
### Expected Behavior

after install ( per the docs) I should be able to check micronaut by running:
mn -version

### Actual Behaviour

brucej@Bruces-MacBook-Pro ~ % mn -verion
zsh: bad CPU type in executable: mn

### Steps To Reproduce

1. Macbook pro, MacOS 13.4.1, Apple M2 Pro
2. follow the install process here: https://micronaut-projects.github.io/micronaut-starter/latest/guide/#installation

### Environment Information

MacOS 13.4.1
either:
    17.0.7 (arm64) "Amazon.com Inc." - "Amazon Corretto 17" /Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home
    11.0.19 (arm64) "Amazon.com Inc." - "Amazon Corretto 11" /Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home

### Version

3.9.4

**Comment by sdelamo** [comment]
Hi, I just installed Micronaut Framework 3.9.4 via sdkman in a MacBook Air M1. 

<img width="1066" alt="CleanShot 2023-06-29 at 19 14 56@2x" src="https://github.com/micronaut-projects/micronaut-starter/assets/864788/5346f4fd-6c48-4130-9d73-60afe88f2d6b">


@micronaut-projects/core-developers can someone with an Apple silicon reproduce this issue?

**Comment by timyates** [comment]
It works for me, but as it's an x86 image, you may need to install Rosetta (if you haven't yet done so)

https://support.apple.com/en-us/HT211861

I believe the command (in a terminal) is:

```
softwareupdate --install-rosetta
```

See also: https://apple.stackexchange.com/questions/408375/zsh-bad-cpu-type-in-executable

Unfortunately, we cannot currently build native arm versions of the `mn` command (until GitHub provides arm osx runners)

**Comment by wetted** [comment]
It works for me on my Silicon Macbook Air, but I think I may have already done something to make it work in the past, and I don't remember what that is. It's possible something else I have caused Rosetta to be installed.

<img width="350"  src="https://github.com/micronaut-projects/micronaut-starter/assets/8419491/694d17cb-c7d8-4dc8-91ee-2f646e2fa79f">

**Comment by brucej72** [comment]
Well, yes - I'm sure that with Rosetta installed this will work. But that was really part of the bug - this doesn't work on an Apple Silicon Mac without an extra translation layer installed. @wetted and @timyates is this just a tooling problem for `mn` or does this have a downstream effect to things like using the toolchain to create native images for aarch?

**Comment by sdelamo** [comment]
I don't think it has any downstream effect. Thanks for reporting.

**Comment by sdelamo** [comment]
Please, note you can also generate applications via [https://launch.micronaut.io](https://launch.micronaut.io). the same code powers the website, powers the CLI.
