### ISSUE TITLE
Several Design changes

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#194]
Current: 

![Screenshot 2020-04-30 at 00 15 25 2@3x](https://user-images.githubusercontent.com/864788/80654794-66e43b80-8a7d-11ea-9ed9-e6df14f44fee.png)

Proposed: 

![Screenshot 2020-04-30 at 00 15 25@3x](https://user-images.githubusercontent.com/864788/80654671-21c00980-8a7d-11ea-9847-5b88ea87f9b3.png)

Changes: 
- [ ] GitHub, twitter, contrast, info button should be of the same height. 
- [ ] Buttons should be on the top right aligned
- [ ] reduce vertical space between micronaut and launch, align the group (micronaut and launch) - with the logo icon. 
- [ ] Radio buttons are stacked horizontally not vertically.
- [ ] Radio buttons are left aligned to the buttons
- [ ] Radio buttons should be aligned with radio buttons titled. 
- [ ] Application Type, Base Package Name and Java version have the same width as the buttons

**Comment by jameskleeh** [comment]
I agree with everything there except the radio buttons. I think them having some vertical space makes it easier to see what you're choosing

**Comment by jameskleeh** [comment]
Most of these things have been implemented

**Comment by kroegerk** [comment]
We can update the logo for you. Stand by.
