### ISSUE TITLE
Remove hardcoded Maven plugin configurations

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-starter#1940]
They are (will be) declared in the parent POM with the current configuration, so in here we should simply declare them and remove hardcoded versions and configurations.

This depends on https://github.com/micronaut-projects/micronaut-platform/issues/663

**Comment by sdelamo** [comment]
I had to revert the commit

**Comment by alvarosanchez** [comment]
In #1947 there was a typo, the group id is:

`org.codehaus.gmavenplus`, but we set it to 

`org.codehaus.gmaven` instead.

**Comment by sdelamo** [comment]
closed via https://github.com/micronaut-projects/micronaut-starter/commit/7f42a2a1d4cdf61d55cdbdf8f7c05d10419e489d
