### ISSUE TITLE
Generated jvmArguments configuration is invalid

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-starter#1942]
This block generates invalid configuration:

https://github.com/micronaut-projects/micronaut-starter/blob/4.0.x/starter-core/src/main/java/io/micronaut/starter/feature/build/maven/templates/pom.rocker.raw#L150-L156

[`jvmArguments` has always been a String and must not contain child elements](https://micronaut-projects.github.io/micronaut-maven-plugin/latest/run-mojo.html#jvmArguments)

**Comment by sdelamo** [comment]
can you explain what should be generated xml if those features are present?

**Comment by alvarosanchez** [comment]
Just a string. For example, for JRebel:

```xml
<jvmArguments>-agentpath:~/bin/jrebel/lib/jrebel6/lib/libjrebel64.dylib</jvmArguments>
```
