### ISSUE TITLE
UI: Text in buttons is cut in mobile

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-starter#195]
The text in the buttons is not center-aligned and is cut in mobile:

![Screenshot_20200430-090032](https://user-images.githubusercontent.com/559192/80681581-43db7b00-8ac1-11ea-974e-5332d33c7255.jpg)

**Comment by graemerocher** [comment]
In a previous version only the icons were displayed on mobile I believe

**Comment by eahrold** [comment]
@ilopmar re-open if you're still seeing this on your device.

**Comment by ilopmar** [comment]
It looks perfect now, thank you Eldon :-)
