### ISSUE TITLE
Inconsistent application names when generating a new project with a hyphenated name

### ISSUE THREAD

**Issue by jon-signal** [micronaut-projects/micronaut-starter#1981]
### Description

When generating a project with a name like "example-hyphenated-name," the application name that appears in the generated `application.properties` file will be "exampleHyphenatedName." This can cause unexpected behavior because `ApplicationConfiguration` just [re-hyphenates the name again](https://github.com/micronaut-projects/micronaut-core/blob/9c73f45b86c1558c73f1bd4cc34ee5282bc199bc/context/src/main/java/io/micronaut/runtime/ApplicationConfiguration.java#L88-L92):

```java
    /**
     * @param name Set the application name
     */
    public void setName(String name) {
        if (name != null) {
            this.name = NameUtils.hyphenate(name);
        }
    }
```

In contexts where application name matching is critical, this can lead to some very unexpected results. In my particular case, I was trying to [read secrets from AWS Secrets Manager](https://micronaut-projects.github.io/micronaut-aws/latest/guide/#distributedconfigurationsecretsmanager) and was very confused when no secrets were found. The issue turned out to be that I was copying the application name from `application.yml` ("myApplication"), but the name Micronaut was actually using when searching for secrets was different ("my-application").

I'll also add that this is especially puzzling behavior because the name I provided at project generation time was already hyphenated, and it got converted to camelCase when it was automatically inserted in `application.yml`. I _think_ the right thing to do here is just leave project names hyphenated in `application.properties`/`application.yml`.

### Steps to Reproduce

1. Visit https://micronaut.io/launch
2. Enter "example-name" as the artifact name
3. Generate the project

### Expected Behaviour

The generated project should consistently use "example-name" as the application/artifact name.

### Actual Behaviour

The generated project uses "exampleName" as the application name in `application.properties`/`application.yml`.

**Comment by sdelamo** [comment]
@jon-signal what you want is that if you enter `raw-tomatoes` in Micronaut Launch.

`application.properties` should contain:

`micronaut.application.name=raw-tomatoes`

currently it contains

`micronaut.application.name=rawTomatoes`

**Comment by jon-signal** [comment]
Yes, that's correct.
