### ISSUE TITLE
Cassandra and Testcontainers features missing dependency

### ISSUE THREAD

**Issue by wetted** [micronaut-projects/micronaut-starter#1982]
Projects with both Cassandra and Testcontainers features should include the [missing] dependency for 

`testImplementation('org.testcontainers:cassandra')`

This is necessary for creating a container using, e.g.: `new CassandraContainer(DockerImageName.parse("cassandra:latest"))`

**Comment by sdelamo** [comment]
@wetted is this done?

**Comment by wetted** [comment]
> @wetted is this done?

No, I can knock this one out now. Won't take long.
