### ISSUE TITLE
Add features for Groovy optional modules

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#2008]
@paulk-asert

> Also, would it make sense to have the Groovy optional modules as features that could be added by launch? E.g. The "groovy-datetime" would add the "groovy-datetime" module. Can this be done just for when the Groovy language is selected? Probably doesn't make sense to use those from other languages, even though it is just a Java library in this case for instance.

**Comment by sdelamo** [comment]
@paulk-asert

which modules do you think we should add? `groovy-datetime` `groovy-json`?

**Comment by paulk-asert** [comment]
I was thinking:

- `groovy-datetime`
- `groovy-dateutil`
- `groovy-ginq`
- `groovy-json`
- `groovy-sql`
- `groovy-toml`
- `groovy-xml`
- `groovy-yaml`

I haven't checked whether any might have dependency conflicts with existing dependencies. There is also the possibility of folks just wanting them in test code not prod code.

**Comment by sdelamo** [comment]
are you interested/do you have time to contribute this PR @paulk-asert  ? I can guide you about how starter code works.

**Comment by wetted** [comment]
@sdelamo A couple things?

- what category do you think these should be in? `Category.LANGUAGE`, `Category.API`, maybe a new one for `Category.GROOVY_MODULE`?
- I think selecting these should be valid for `Language.GROOVY` and/or `TestFramework.SPOCK`
