### ISSUE TITLE
Read default Micronaut Version from API

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-starter#201]
The Micronaut version being used to create apps is currently a hard coded constant in the React app.

We should read the version from the API using https://launch.micronaut.io/versions

**Comment by eahrold** [comment]
We may also want to expose an endpoint the provides all of the supported versions, since that option array is hard coded too.

**Comment by graemerocher** [comment]
Thinking about this I think we should leave them as constants such as:

```js
export const MICRONAUT_VERSIONS = [
    {label:"2.0.0.M3", value:"2.0.0.M3", api:"https://launch.micronaut.io"},
    {label:"2.0.0.BUILD-SNAPSHOT", value:"BUILD-SNAPSHOT, api:"https://micronaut-starter-staging-ucxwqnh6ka-uc.a.run.app"}
];
```

But instead update the `release.yml` of this project to update the versions on each release.

We do need to add functionality to the UI though so that when the user selects a different version it switches the API endpoint and reloads the features etc. This is probably covered in #202

**Comment by sdelamo** [comment]
I think this is done. Please @eahrold reopen it if it if is not.
