### ISSUE TITLE
Support the Micronaut 2.0.0 snapshot

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-starter#202]
We should have a radio button to switch to using the snapshot API for Micronaut 2.0.0 snapshot 

We maybe want to consider creating snapshot.micronaut.io as a subdomain

**Comment by eahrold** [comment]
I've got this started as a bit of a WIP, https://github.com/micronaut-projects/static-website/tree/feature/micronaut-versions

There may need to be CORS adjustments to the API as it stands.
