### ISSUE TITLE
Scrollbar hidden

### ISSUE THREAD

**Issue by benmccann** [micronaut-projects/micronaut-starter#203]
When I load https://micronaut.io/launch/ in Chrome and click "+ Features" the scrollbar control is hidden under "Search Features" in the modal that pops up. I can see the bottom of the scrollbar and click it to scroll down and eventually the scrollbar control will emerge

**Comment by eahrold** [comment]
Yeah, That’s due to the fixed header. I’ll see I’d swapping padding for margin helps.
