### ISSUE TITLE
Update Starter to generate projects with both either 17 and 21

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#2051]
We will need to have a validator for certain features which don't support 21. 

For example,  Lambda will probably not have a Java 21 runtime on day one.

**Comment by timyates** [comment]
This requires [Gradle 8.4 (currently)](https://docs.gradle.org/current/userguide/compatibility.html#java), which at time of writing isn't out

**Comment by sdelamo** [comment]
can this be closed?

**Comment by timyates** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-starter/pull/2142 for Micronaut 4.2.0
