### ISSUE TITLE
Build mn for Arm macs

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-starter#2107]
Currently we ship the x86 binary for ARM apple devices.

This can cause issues if people haven't previously enabled rosetta on their device.

Github have just announced Arm runners for OSX

https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

We should use these to generate Arm binaries of MN and push them to SDKman instead of the x86 one currently

**Comment by sdelamo** [comment]
does sdkman allow us to ship different version per os and architecture?

**Comment by timyates** [comment]
Yes, you can see us doing it here (pushing amd64 to both ARM and OSX variants of Mac

https://github.com/micronaut-projects/micronaut-starter/blob/15cf111b01ee992d175b9abcb857509fbea63c90/starter-cli/build.gradle#L87-L93

**Comment by timyates** [comment]
Looks like I was too eager...

So there are arm runners, but they are `macos-latest-xlarge` not free, and trying to use them results in 

>The job was not started because recent account payments have failed or your spending limit needs to be increased. Please check the 'Billing & plans' section in your settings.

Which is a shame

Closing this for now, but I'll keep my eye out to see if a free layer gets added later on
