### ISSUE TITLE
Vertx MySQL defaults to incorrect port

### ISSUE THREAD

**Issue by eahrold** [micronaut-projects/micronaut-starter#213]
From https://vertx.io/docs/vertx-mysql-postgresql-client/java/

port
The port of the database. Defaults to 5432 for PostgreSQL and 3306 for MySQL

![2780B435-DB6F-4237-A8A2-0A8118C1C94D](https://user-images.githubusercontent.com/3740088/80853233-9b2e3800-8bf4-11ea-96a5-2355e5aa5486.png)

**Comment by ilopmar** [comment]
You need to fix the test: https://github.com/micronaut-projects/micronaut-starter/blob/master/starter-core/src/test/groovy/io/micronaut/starter/feature/vertx/VertxClientSpec.groovy#L48
I think you can also rename the test to `VertxMysqlSpec.groovy`
