### ISSUE TITLE
Add flyway dependency for postgresql database support.

### ISSUE THREAD

**Issue by wetted** [micronaut-projects/micronaut-starter#2168]
See https://github.com/micronaut-projects/micronaut-flyway/pull/472

As of flyway v10.0.0, the following dependency is also required for postgres database support: `org.flywaydb:flyway-database-postgresql`. Include this when flyway and postrges features are selected.

**Comment by sdelamo** [comment]
closed via https://github.com/micronaut-projects/micronaut-starter/pull/2170
