### ISSUE TITLE
Add hasExclusion API to BuildTestVerifier

### ISSUE THREAD

**Issue by wetted** [micronaut-projects/micronaut-starter#2172]
In addition to testing for dependencies we need to test for exclusions to specific dependencies, and in specific scopes.

**Comment by wetted** [comment]
ping @timyates 

`hasExclusion(String groupId, String artifactId, String exludedGroupId, String excludedArtifactId)`
`hasExclusion(String groupId, String artifactId, String exludedGroupId, String excludedArtifactId, Scope scope)`

plus hellish regex 🥴

**Comment by timyates** [comment]
👍 For maven it will be much simpler xml navigation, but for Gradle we'll have to do some regex (which allows for Gradle and Gradle_kotlin) as there's no parser for Gradle build scripts 😿
