### ISSUE TITLE
Selecting Groovy, Mongo and GORM produces invalid applications

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-starter#218]
Partially caused by https://github.com/micronaut-projects/micronaut-core/issues/3149

The root cause is that GORM only supports Mongo driver up to 3.x. However, latest `micronaut-mongodb` uses 4.x driver.

It affects `mongo-gorm` and `mongo-reactive` features.

The solution until GORM for MongoDB is upgraded to 4.x drivers is to pin the following versions:

```groovy
configurations.all {
    resolutionStrategy {
        force "org.mongodb:mongo-java-driver:3.10.0"
        force "org.mongodb:mongodb-driver-async:3.10.0"
        force "io.micronaut.configuration:micronaut-mongo-reactive:1.1.0"
    }
}
```

Mongo version could be `3.10.0` or the latest `3.x`.

A fully working application is at https://github.com/alvarosanchez/micronaut2x-gorm-mongodb

**Comment by jameskleeh** [comment]
@alvarosanchez Please verify this is now working as expected

**Comment by alvarosanchez** [comment]
Tried mongo-gorm, mongo-reactive and mongo-sync, they all work.
