### ISSUE TITLE
create `create-chatbot-telegram` CLI command 

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#2229]
> $ create-chatbot-telegram
> 
> How do you want to deploy it?
> 
> *1) AWS Lambda Function
> 2) Google Cloud Function
> 3) Azure Function

ApplicationType will be `FUNCTION` automatically. 

For Lambda the `aws-lambda-function-url` feature is added automatically.

For Lambda the following two questions will be asked: 

> 
> How do you want to deploy?. (enter for Java runtime)
> *1) Fat JAR running in the managed Java runtime
>  2) Native executable built with GraalVM Native Image running in a custom runtime. Faster cold start
> > 
> 
> Choose your Lambda Architecture. (enter for x86)
>  1) arm
> *2) x86
> > 

> 
> Do you want to generate infrastructure as code with CDK? (enter for yes)
> *1) YES
>  2) NO

for every cloud the follow questions will be asked ask well. 

> Choose your preferred language. (enter for default)
> *1) Java
>  2) Groovy
>  3) Kotlin
> > 
> 
> Choose your preferred test framework. (enter for default)
> *1) JUnit
>  2) Spock
>  3) Kotest
> > 
> 
> Choose your preferred build tool. (enter for default)
>  1) Gradle (Groovy)
> *2) Gradle (Kotlin)
>  3) Maven
> > 
> 
> Choose the target JDK. (enter for default)
> *1) 17
> > 
> 

> Enter any features to apply. Use tab for autocomplete and separate by a space.

See `create-aws-lambda` command. There is a lot of common code. 

[Azure functions support only 17. ](https://learn.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=isolated-process%2Cv4&pivots=programming-language-java)

[Google Cloud function support 21 but only in 2nd gen preview only](https://cloud.google.com/functions/docs/concepts/java-runtime)

AWS Lambda supports 21

**Comment by timyates** [comment]
Closed by https://github.com/micronaut-projects/micronaut-starter/pull/2245
