### ISSUE TITLE
Remove unsupported gorm features for Micronaut 4.

### ISSUE THREAD

**Issue by wetted** [micronaut-projects/micronaut-starter#2268]
GORM is not supported in Micronaut Framework 4. Remove the following features from starter for 4.x projects: hibernate-gorm, mongo-gorm, multi-tenancy-gorm and neo4j-gorm.

**Comment by sdelamo** [comment]
go ahead

**Comment by awesomekosm** [comment]
So gorm is forever removed from micronaut 4? Is there a migration path instead of rewriting entire db layer?

**Comment by aadrian** [comment]
Not being able to use GORM in Micronaut is a huge step back :( .

**Comment by wetted** [comment]
@awesomekosm @aadrian Micronaut 4 uses Groovy 4 and GORM does not [yet] support it. See https://github.com/micronaut-projects/micronaut-groovy/issues/422

N.B.: https://github.com/micronaut-projects/micronaut-core/issues/10486

**Comment by awesomekosm** [comment]
@wetted it's all over the latest documentation, as if it works. When is the estimated time when it will be supported? It's a lot of throw away code written using gorm...

**Comment by sdelamo** [comment]
GORM does not support Groovy 4 yet. Micronaut Framework 4 Groovy baseline is Apache Groovy 4. If you want to use GORM with Micronaut Framework I recommend you to keep at Micronaut Framework 3.

**Comment by sdelamo** [comment]
> @wetted it's all over the latest documentation, as if it works. When is the estimated time when it will be supported? It's a lot of throw away code written using gorm...

in which documentation is it? we should remove it.

**Comment by wetted** [comment]
> > @wetted it's all over the latest documentation, as if it works. When is the estimated time when it will be supported? It's a lot of throw away code written using gorm...
> 
> in which documentation is it? we should remove it.

@sdelamo I just looked. We have it in the core user guide still. I created this issue for that: https://github.com/micronaut-projects/micronaut-core/issues/10689. I can work on this next week I think.

**Comment by wetted** [comment]
> > > @wetted it's all over the latest documentation, as if it works. When is the estimated time when it will be supported? It's a lot of throw away code written using gorm...
> > 
> > 
> > in which documentation is it? we should remove it.
> 
> @sdelamo I just looked. We have it in the core user guide still. I created this issue for that: [micronaut-projects/micronaut-core#10689](https://github.com/micronaut-projects/micronaut-core/issues/10689). I can work on this next week I think.

This PR removes the obsolete docs for GORM: https://github.com/micronaut-projects/micronaut-core/pull/10696
