### ISSUE TITLE
Can't download AWS 2.0.0.M3 - incorrect BOM version

### ISSUE THREAD

**Issue by rsmogura** [micronaut-projects/micronaut-starter#228]
Hi Micronaut team,

I hope you have a good day and thanks for nice tool. 

We have found simple issue - when resolving 2.0.0.M3 dependencies, looks like that there's incorrect version specifier for BOM dependency management: **2.0.0.BUILD-SNAPSHOT**

```
Could not resolve io.micronaut.starter:micronaut-starter-aws-lambda:2.0.0.M3.
         > Could not parse POM https://jcenter.bintray.com/io/micronaut/starter/micronaut-starter-aws-lambda/2.0.0.M3/micronaut-starter-aws-lambda-2.0.0.M3.pom
            > Could not find io.micronaut:micronaut-bom:2.0.0.BUILD-SNAPSHOT.
              Searched in the following locations:
```

**Comment by jameskleeh** [comment]
@rsmogura That module shouldn't have been published at all. You can reference the source at that tag and build it locally
