### ISSUE TITLE
KTOR feature doesn't add a KTOR server

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-starter#232]
The KTOR feature is broken because it doesn't add a KTOR server. As a minimum the following should be added:

```
implementation "io.ktor:ktor-server-netty:1.3.2"
```

**Comment by graemerocher** [comment]
Also the KTOR application class has to look like:

https://github.com/micronaut-projects/micronaut-kotlin/blob/master/examples/greeting/src/main/kotlin/app/Application.kt

**Comment by sdelamo** [comment]
I've set a slightly modified version of `Application.kt`. So that the app can be start it with `./gradlew run`. 

```kotlin
package com.example
import io.ktor.server.netty.NettyApplicationEngine
import io.micronaut.ktor.KtorApplication
import io.micronaut.ktor.runApplication
import javax.inject.Singleton

@Singleton
class KtorApp : KtorApplication<NettyApplicationEngine.Configuration>({
})
object Application {
    @JvmStatic
    fun main(args: Array<String>) {
        runApplication(args)
    }
}
```
