### ISSUE TITLE
Selecting Java 21 application is generated with 17

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#2321]
![CleanShot 2024-02-09 at 15 48 52@2x](https://github.com/micronaut-projects/micronaut-starter/assets/864788/5751f10c-7a93-4183-b33e-8fda26a4d8d8)
![CleanShot 2024-02-09 at 15 48 34@2x](https://github.com/micronaut-projects/micronaut-starter/assets/864788/9d99cabc-5e09-44f4-9c0e-d87fa058305c)

**Comment by timyates** [comment]
@wetted I think this is caused by https://github.com/micronaut-projects/micronaut-starter/pull/2192

As it's no longer an Enum, we need a Singleton `TypeConverter<String, JdkVersion>` bean to convert the String in the query to a JdkVersion

**Comment by wetted** [comment]
> @wetted I think this is caused by #2192
> 
> As it's no longer an Enum, we need a Singleton `TypeConverter<String, JdkVersion>` bean to convert the String in the query to a JdkVersion

Thanks Tim. I'll address that tomorrow. I at least now have a bunch of tests to prevent a regression once it's fixed.
