### ISSUE TITLE
Add missing `replaceLogbackXml` in `aot` section

### ISSUE THREAD

**Issue by melix** [micronaut-projects/micronaut-starter#2418]
In the Micronaut AOT configuration block, we miss the logback conversion:

```
aot {
   ...
   replaceLogbackXml = true
}
```

**Comment by wetted** [comment]
@melix @alvarosanchez 

I found this in `micronaut-maven-plugin` (`aot.properties` files in a couple places under integration tests)

```
# Replaces logback.xml with a pure Java configuration (NOT YET IMPLEMENTED!)
logback.xml.to.java.enabled = false
```

Should I ignore this for now and not add it for starter Maven projects? I assume leave it out until it's implemented.

**Comment by melix** [comment]
I think it's a mistake in the Maven plugin, this has been implemented for months, it's just that the configuration file hasn't been updated.

**Comment by wetted** [comment]
> I think it's a mistake in the Maven plugin, this has been implemented for months, it's just that the configuration file hasn't been updated.

OK. Thanks. I will also add it in starter.
