### ISSUE TITLE
Creating Azure/GCP function results in an app with Lambda stuff in it

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-starter#244]
Running:

```
$ mn create-function-app example --features google-cloud-function
```

The aws lambda dependencies and sources exist in the created app (`BookRequestHandler` etc.)

**Comment by sdelamo** [comment]
Already fixed via: https://github.com/micronaut-projects/micronaut-starter/commit/523a48c45c48a2eadad8d3975dc7dcc859375ec3
