### ISSUE TITLE
Groovy and Maven Unable to determine Groovy Version

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#246]
The build was broken. I have added this commit to get the build green again: 

https://github.com/micronaut-projects/micronaut-starter/commit/f87e5d9d14a1e1fdd907c3a091a033adcdda6b7c

Creating app 

`% ./gradlew micronaut-cli:run --args="create-app --lang=groovy --test=junit --build=maven temp"`

This is the error: 

```
[INFO] --- gmavenplus-plugin:1.9.0:generateStubs (default) @ temp ---
[INFO] Using isolated classloader, without GMavenPlus classpath.
[INFO] Unable to get Groovy version from GroovySystem, trying InvokerHelper.
[WARNING] Unable to get Groovy version from InvokerHelper or GroovySystem, trying jar name.
[ERROR] Unable to determine Groovy version. Is Groovy declared as a dependency?
```

The issue seems to be related with Micronaut `2.0.0.BUILD-SNAPSHOT`. Setting `2.0.0.M3`fixes the issue.

**Comment by sdelamo** [comment]
I tried deleting .m2 as recommeded here: https://github.com/groovy/GMavenPlus/issues/84 but it did not help.

**Comment by jameskleeh** [comment]
This seems to be because of how the transitive for inject-groovy is being resolved. 

M3:
```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ demo ---
[INFO] com.example:demo:jar:0.1
[INFO] +- io.micronaut:micronaut-inject-groovy:jar:2.0.0.M3:provided
[INFO] |  \- org.codehaus.groovy:groovy:jar:2.5.10:compile
```

Snapshot:
```
INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ demo ---
[INFO] com.example:demo:jar:0.1
[INFO] +- io.micronaut:micronaut-inject-groovy:jar:2.0.0.BUILD-SNAPSHOT:provided
[INFO] |  \- org.codehaus.groovy:groovy:jar:3.0.3:runtime
```

Note `compile` vs `runtime`

**Comment by sdelamo** [comment]
Ignored tests were reverted https://github.com/micronaut-projects/micronaut-starter/commit/01d96573a77c334d2ee7c204e9db0f1f93a6f2bc

Thus, Build fails again: https://github.com/micronaut-projects/micronaut-starter/actions/runs/114424072

**Comment by sdelamo** [comment]
@jameskleeh I have reverted the commit to revert the ignore tests. I want the CI to be operational to be able deploy new versions, run build for other commits etc.

**Comment by jameskleeh** [comment]
Then work on a branch. Ignoring tests on master shouldn’t be done
