### ISSUE TITLE
Remove RxJava1 and RxJava2 feature for Micronaut Framework 5

### ISSUE THREAD

**Issue by wetted** [micronaut-projects/micronaut-starter#2463]
RxJava2 is removed from `micronaut-platform` BOM on https://github.com/micronaut-projects/micronaut-platform/pull/1427. The feature needs to be removed from starter too (CI fails otherwise).

micronaut-rxjava1 is also obsolete, so that should be removed as well.

**Comment by wetted** [comment]
This is meant to address the failures at https://ge.micronaut.io/s/d5nvdzxxzsqec/tests/overview?outcome=FAILED.

The particular test failures here is a bit more complex. The test that fails is `KubernetesClientSpec` test cases that build with the `kubernetes-rxjava2-client` feature. That feature adds a dependency on `io.reactivex.rxjava2:rxjava`, but with `micronaut-rxjava2` removed from `micronaut-platform`, the BOM no longer exposes the version for `io.reactivex.rxjava `dependency. What do we do about that?

Should we add `io.reactivex.rxjava2:rxjava` as a managed dependency in `micronaut-kubernetes`, or what?

I still think we should remove features from starter for modules we remove from platform, but this is a different problem.

**Comment by sdelamo** [comment]
> Should we add io.reactivex.rxjava2:rxjava as a managed dependency in micronaut-kubernetes, or what?

No. No module in Micronaut Framework 5 should depend or expose Micronaut 5. Remove RxJava 2 features from starter in 5.0.x branch.
