### ISSUE TITLE
Generate native ARM binaries for OSX

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-starter#2473]
Currently we ship an x86 binary for both the arm and x86 channels of SDKMan, then let Rosetta sort it out on the client machine.

[We tried previously to generate an ARM binary](https://github.com/micronaut-projects/micronaut-starter/issues/2107) but at the time there were no ARM runners to build on.

Yesterday, Github switched the `macos-latest` runner across to OSX 14, and it only runs on ARM hardware.

So we should use `macos-latest` to generate the ARM binary.

And `macos-13` to generate the x86 binary.

And then push the correct binary to the correct SDKMan channel

**Comment by breun** [comment]
The MacPorts port now also uses the aarch64 binary on arm64 machines: https://github.com/macports/macports-ports/pull/23820/files
