### ISSUE TITLE
Latest snapshot artifacts are zipped twice!

### ISSUE THREAD

**Issue by aadrian** [micronaut-projects/micronaut-starter#248]
### Description

The latest Snapshot Artifacts for the CLI are zipped twice (a zip archive inside another zip archive with the same name)

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Go to the https://github.com/micronaut-projects/micronaut-starter/actions pate
2. Download on of the latest CLI snapshots there, e.g. https://github.com/micronaut-projects/micronaut-starter/actions/runs/114575561  or https://github.com/micronaut-projects/micronaut-starter/actions/runs/114575546
3. Unpack this distribution somewhere

### Expected Behaviour
After unpacking, one would expect to see the directory containing the CLI project artifacts.

### Actual Behaviour
After unpacking the distribution, there's another ZIP archive (so it the distribution was packed twice)

**Comment by graemerocher** [comment]
The reason for this is github actions basically automatically zips build assets (which happen to be zip files)

**Comment by aadrian** [comment]
> The reason for this is github actions basically automatically zips build assets (which happen to be zip files)

@graemerocher  indeed, there seems to be at least one open GitHub Action Issue for this https://github.com/actions/upload-artifact/issues/39

**Comment by graemerocher** [comment]
Not much can be done so closing
