### ISSUE TITLE
Project group name is wrong

### ISSUE THREAD

**Issue by andlbrei** [micronaut-projects/micronaut-starter#2528]
### Expected Behavior

A working starter app using the feature `json-schema` when running
`mn create-app --build=gradle_kotlin --jdk=21 --lang=java --test=junit --features=json-schema com.example.json-schema`

### Actual Behaviour

Micronaut Launch/create-app does not work because the name of the project group is wrong.

Micronaut Launch uses `.json-schema`, while the actual name of the dependency is `.jsonschema`.
`implementation("io.micronaut.jsonschema:micronaut-json-schema-annotations")`
vs
`implementation("io.micronaut.json-schema:micronaut-json-schema-annotations")`

Based on what the naming convention seems to be for Micronaut modules, this group should be called `json-schema`?

Either way, the starter is not working.

### Steps To Reproduce

1. run `mn create-app --build=gradle_kotlin --jdk=21 --lang=java --test=junit --features=json-schema com.example.json-schema`
2. Build and observe the error
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':optimizedJitJarAll'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
   > Could not find io.micronaut.json-schema:micronaut-json-schema-annotations:.
     Required by:
         project :
```

### Environment Information

- macOS Sonoma 14.5
- Eclipse temurin-21

### Version

4.5.0

**Comment by graemerocher** [comment]
needs to be fixed in launch
