### ISSUE TITLE
Question Regarding CRaC Feature Status on Micronaut Launch – Still in Preview?

### ISSUE THREAD

**Issue by rjaros87** [micronaut-projects/micronaut-starter#2661]
### Issue description

I noticed that when using the [Micronaut Launch](https://micronaut.io/launch/) page, the CRaC (Coordinated Restore at Checkpoint) feature is still marked as `Preview`. Given that Azul's CRaC project has released production-ready builds and several frameworks have integrated CRaC for production use, I wanted to clarify the current status of CRaC in Micronaut.

1. Is the Preview label on the launch page accurate, and is CRaC still not considered production-ready within the Micronaut framework?
2. If CRaC support is still in development or pending further testing, could you provide details on what remains to be done before it reaches production status?
3. Alternatively, if this is an oversight, could the label on the feature list be updated to reflect its current status?
Thank you for your time, and I appreciate all the great work being done with Micronaut!

**Comment by rjaros87** [comment]
Is this project still supported / alive? :) 
@sdelamo maybe you know something about this?
Thanks in advance.

**Comment by sdelamo** [comment]
I will remove the preview flag. thanks for the heads up.
