### ISSUE TITLE
Wrong Content-type parameter in Create-Application request response header

### ISSUE THREAD

**Issue by vladimir-petrenko** [micronaut-projects/micronaut-starter#268]
### Description

Hi!
When I try to get a generated Micronaut project from https://launch.micronaut.io by HTTP GET request of type `https://launch.micronaut.io/create/{type}/{name}`, a header of received response contains `Content-Type` parameter with `text/html` value. However this parameter should be `application/zip`, because:
1. This is specified in OpenAPI https://launch.micronaut.io/swagger/micronaut-starter-2.0.0.BUILD-SNAPSHOT.yml (look at `paths:` -> `/create/{type}/{name}:` -> `responses:` -> `content:`)
2. Received response contains a `*.zip` file

### Steps to Reproduce

1. Make HTTP GET request https://launch.micronaut.io/create/default/untitled?build=GRADLE&test=JUNIT&lang=JAVA&javaVersion=JDK_8
2. Look at a header of received response

### Expected Behaviour

`Content-Type` parameter should be `application/zip`

### Actual Behaviour

`Content-Type` parameter is `text/html`

**Comment by graemerocher** [comment]
Seems to be fixed in the snapshot API:

```
$ curl -i https://snapshot.micronaut.io/create/default/untitled\?build\=GRADLE\&test\=JUNIT\&lang\=JAVA\&javaVersion\=JDK_8
HTTP/2 201 
content-disposition: attachment; filename=untitled.zip
content-type: application/zip
date: Mon, 08 Jun 2020 12:29:33 GMT
server: Google Frontend
content-length: 57015
```

**Comment by vladimir-petrenko** [comment]
> Seems to be fixed in the snapshot API:
> ...

Indeed, it is.

Will it be fixed for **launch**.micronaut.io? And when? (if you can answer)

I'm asking in because we are implementing a New Project Wizard for Micronaut in IntellijJ IDEA using this API (https://youtrack.jetbrains.com/issue/IDEA-222140).

**Comment by graemerocher** [comment]
yes it will be fixed in the next release will will go out on the 15h of June, in the meantime you can use the snapshot API. 

It is probably worth allowing users to generate applications with the snapshot as well

**Comment by vladimir-petrenko** [comment]
Nice! 
Thanks for answering)
