### ISSUE TITLE
Create a centralized file where version numbers exposed by features are defined

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#270]
For example the `asciidoc` feature: 

https://github.com/micronaut-projects/micronaut-starter/blob/master/starter-core/src/main/java/io/micronaut/starter/feature/asciidoctor/template/asciidocGradle.rocker.raw

Or the test containers feature: 

https://github.com/micronaut-projects/micronaut-starter/pull/266

Maybe `src/main/resources/versions.properties`

**Comment by alvarosanchez** [comment]
We now have `VersionInfo` that can get dependencies from the BOM
