### ISSUE TITLE
Get the Micronaut versions from API endpoints, instead of hardcoding them

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-starter#289]
In order to avoid having to create commits like https://github.com/micronaut-projects/static-website/commit/974b861d4cae9bc7801089a24306666c39ec8220 after every release, the frontend instead should query the Launch API to determine the 2 versions it needs:

* Latest release: https://launch.micronaut.io/versions
* Snapshot version: https://snapshot.micronaut.io/versions

Both expose the version under the `micronaut.version` key.

**Comment by JasonTypesCodes** [comment]
@alvarosanchez FYI, currently `micronaut.version` in both the snapshot and latest URLs above is `2.0.0.RC2`

**Comment by alvarosanchez** [comment]
> @alvarosanchez FYI, currently `micronaut.version` in both the snapshot and latest URLs above is `2.0.0.RC2`

Yes, we are aware of that. @ilopmar will fix it

**Comment by ilopmar** [comment]
I think we should be more flexible and provide more versions. Not going to happen in a naer future, but we will have something like:
2.1.0-SNAPSHOT, 2.0.3-SNAPSHOT and 2.0.2.
