### ISSUE TITLE
SSL error on Micronaut Launch page prevents usage

### ISSUE THREAD

**Issue by thecodesmith** [micronaut-projects/micronaut-starter#291]
### Description

Micronaut Launch web application is unusable due to empty options.

### Steps to Reproduce

1. Visit https://micronaut.io/launch/ in browser (tested using Safari)
### Expected Behaviour

Can select Application Type, Features, Preview, etc. and generate application

### Actual Behaviour

Opening https://micronaut.io/launch/ causes this error in a red popup:
```
An SSL error has occurred and a secure connection to the server cannot be made.
```
Clicking any of the buttons (Application Type, Features, Preview) results in either another error popup, or just empty options.

### Environment Information

- **Operating System**: macOS 10.15
- **Browser**: Safari

**Comment by graemerocher** [comment]
Can't reproduce this personally, nor can anyone I have spoken to

**Comment by thecodesmith** [comment]
It does appear to be working now for me also. 👍
