### ISSUE TITLE
Swagger UI doesn't load openapi.yml file

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-starter#329]
This is not working https://launch.micronaut.io/swagger/views/swagger-ui/index.html

The snapshot version works: https://snapshot.micronaut.io/swagger/views/swagger-ui/

**Comment by graemerocher** [comment]
yes it is fixed in the snapshot, why did you raise an issue for something already fixed? 😉

**Comment by ilopmar** [comment]
hahaha, in my head it compiled but now that you say, it doesn't make any sense. You know, it's Friday! :joy:
