### ISSUE TITLE
Feature Request: build.gradle.kts

### ISSUE THREAD

**Issue by dkowis** [micronaut-projects/micronaut-starter#340]
For Kotlin projects using Gradle, at least, but I think it has value for all Gradle projects, generate a `build.gradle.kts` (same with `settings.gradle.kts`) instead of a groovy-based `build.gradle`.

Type safety! Easier Refactoring! IDE support in the build script!

**Comment by ilopmar** [comment]
There is a pending PR (outdated) #50 for that.

**Comment by ilopmar** [comment]
Duplicated #342

**Comment by dkowis** [comment]
Oof, I did search for this, must not have searched very well. Sorry!

**Comment by graemerocher** [comment]
No worries, thanks for the feedback!
