### ISSUE TITLE
Missing entries from .gitignore

### ISSUE THREAD

**Issue by benmccann** [micronaut-projects/micronaut-starter#341]
I had the following created in my project, which I don't think are supposed to be checked in

`gradle/` - I think this directory is created and files downloaded and put in it by `gradlew`
`.factorypath` - This seems to be related to the Gradle Buildship Eclipse plugin which I installed after the Micronaut docs suggested I use it

**Comment by ilopmar** [comment]
`gradle` directory should be in source control because it contains the files needed to automatically download Gradle when you execute the wrapper: `./gradlew` or `gradlew.bat`.

Can you please point me to where we mention the "Gradle Buildship Eclipse" plugin?

**Comment by benmccann** [comment]
> gradle directory should be in source control because it contains the files needed to automatically download Gradle when you execute the wrapper: ./gradlew or gradlew.bat

You're right. Ignoring the whole directory is too much. But `gradle/wrapper/gradle-wrapper.jar` is not present on new project creation, so I wonder if that file should be ignored

> Can you please point me to where we mention the "Gradle Buildship Eclipse" plugin?

See "Configuring Eclipse IDE": https://docs.micronaut.io/latest/guide/index.html#ideSetup

I'm not quite sure that's where it's coming from. Based on Google search results it definitely seems to be related to Eclipse. It's also possible it's in all Eclipse projects or is coming from the `id "com.diffplug.eclipse.apt" version "3.22.0"` in the `build.gradle` file

**Comment by ilopmar** [comment]
> You're right. Ignoring the whole directory is too much. But gradle/wrapper/gradle-wrapper.jar is not present on new project creation, so I wonder if that file should be ignored

The jar file is also necessary and it is included when you create a new project:

```
ivan@nobita:/tmp$ mn -V                                                        
Micronaut Version: 2.0.0
JVM Version: 1.8.0_252

ivan@nobita:/tmp$ mn create-app foo
| Application created at /tmp/foo

ivan@nobita:/tmp$ cd foo 
ivan@nobita:/tmp$ find gradle  
gradle
gradle/wrapper
gradle/wrapper/gradle-wrapper.jar
gradle/wrapper/gradle-wrapper.properties
```

> See "Configuring Eclipse IDE": https://docs.micronaut.io/latest/guide/index.html#ideSetup
> 
> I'm not quite sure that's where it's coming from. Based on Google search results it definitely seems to be related to Eclipse. It's also possible it's in all Eclipse projects or is coming from the id "com.diffplug.eclipse.apt" version "3.22.0" in the build.gradle file

TBH we don't use Eclipse, we develop with IntelliJ. Using only IntelliJ and having `id "com.diffplug.eclipse.apt" version "3.22.0"` defined doesn't create that file.

If you think we really need to exclude `.factorypath` from source control, please open an issue in https://github.com/micronaut-projects/micronaut-starter and submit a PR to add it here https://github.com/micronaut-projects/micronaut-starter/blob/b8d732fd088a561816f35488375feecec0b67815/starter-core/src/main/java/io/micronaut/starter/feature/build/gitignore.rocker.raw
