### ISSUE TITLE
Support for -build parameter option like "kotlindsl" or "gradle-kotlin" to build "build.gradle.kts" file

### ISSUE THREAD

**Issue by C06A** [micronaut-projects/micronaut-starter#342]
In addition to options "gradle" and "maven" I suggest to support the 3rd one to use Gradle with KotlinDSL syntax. This especially useful in case of language "kotlin". However some people may prefer it even for Java (probably not for Groovy ;-) ).

I can provide the file build.gradle.kts converted from build.gradle.

### Expected Behaviour

The run CLI "mn" with option "-build kotlindsl" will create required new project with file "build.gradle.kts" instead of "build.gradle" and "settings.gradle.kts" instead of "settings.gradle".

### Actual Behaviour

Currently this flag is not supported

### Environment Information

- **Operating System**: Mac OSX 10.14.1
- **Micronaut Version:** 1.0.1
- **JDK Version:** 1.8.0_112

**Comment by alvarosanchez** [comment]
Did #50 fix this?
