### ISSUE TITLE
Preview pane is missing file

### ISSUE THREAD

**Issue by benmccann** [micronaut-projects/micronaut-starter#344]
### Description

`gradle/wrapper/gradle-wrapper.jar` is missing from preview pane, but is included in newly created projects

### Steps to Reproduce

1. Go to https://micronaut.io/launch/
2. Click "PREVIEW"
3. Expand `gradle/wrapper` directories

### Expected Behaviour

Should see `gradle-wrapper.jar`. This file is present when downloading the project or creating via the command line

### Actual Behaviour

`gradle-wrapper.jar` is missing

### Environment Information

Left all settings as default:

- Version: 2.0.0
- Build: Gradle

**Comment by ilopmar** [comment]
Ohh, I see. That's not an issue. The file is not displayed there because it's a binary file so we can't really display it. Maybe we can add an improvement to show the file on the tree but not allowing to select it.

**Comment by benmccann** [comment]
Yeah, that'd be helpful. I thought that file wouldn't exist in a new project based on what I was seeing in the preview pane. I don't need to see the contents obviously, so making it non-selectable would be fine. Or maybe allowing to download it, but that's less of an issue since I can generate a new project to get the file if I know it exists and is missing in my project.

**Comment by ilopmar** [comment]
I've opened a new feature request: https://github.com/micronaut-projects/micronaut-starter/issues/346

**Comment by ilopmar** [comment]
Thanks for your feedback!
