### ISSUE TITLE
API Documentation is not available

### ISSUE THREAD

**Issue by jreznot** [micronaut-projects/micronaut-starter#351]
### Description

API Link mentioned in README no longer works: https://launch.micronaut.io/swagger/views/swagger-ui/index.html

### Task List

- [X]  Steps to reproduce provided
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Open https://launch.micronaut.io/swagger/views/swagger-ui/index.html

### Expected Behaviour

Swagger API docs shown.

### Actual Behaviour

Failed to load API definition.
![image](https://user-images.githubusercontent.com/1066152/88163085-d56b0c80-cc1a-11ea-97dd-a8a7b224972b.png)

**Comment by graemerocher** [comment]
We are aware, will be fixed in the next release. Sorry about that.

You can use the snapshot in the meantime https://snapshot.micronaut.io/swagger/views/swagger-ui/index.html

**Comment by ilopmar** [comment]
This was fixed in 2.0.1
