### ISSUE TITLE
Breaking the micronaut.io/launch/ wizard with name=micronaut

### ISSUE THREAD

**Issue by JaroslavTulach** [micronaut-projects/micronaut-starter#352]
I have just tried the wizard at https://micronaut.io/launch/ and I got a ZIP file which isn't compilable. My input was:

* Application, JDK14, pkg=org.xelfi.test, name=micronaut
* 2.0.0, Java, Maven, JUnit

I got the following error when invoking `mvn package`:
```
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ 
micronaut ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /micronaut/target/test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /micronaut/src/test/java/org/xelfi/test/MicronautTest.java:[4,1] 
org.xelfi.test.MicronautTest is already defined in this compilation unit
[INFO] 1 error
```

Initial investigation by Graeme:

> Interesting error. It seems you have a test called “MicronautTest” 
> which conflicts with the @MicronautTest annotation. You would have to qualify the 
> import for `@MicronautTest` if you want a test of the same name.

Yes, the broken sample is very likely result of specifying `micronaut` as name of my application.

**Comment by graemerocher** [comment]
Look like we need to return an error if `micronaut` is the name used for the app
