### ISSUE TITLE
Expose the default JDK version

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-starter#366]
Instead of hard-coding the default to JDK11 it would be better to expose it in a new API endpoint so external clients like the UI and IntelliJ new project wizard can use it.

Related to https://youtrack.jetbrains.com/issue/IDEA-246318

**Comment by jameskleeh** [comment]
@ilopmar I don't understand the need for this. Any external client can make their own determination about the default JDK. No one is forced to use what we do.

**Comment by ilopmar** [comment]
This came from a discussion with the JetBrains folks asking for an endpoint to the default JDK to be used in the new "Create new project" wizard in IntelliJ. This way they can mimic our Launch options without hardcoding them.

**Comment by jameskleeh** [comment]
We now have an API for this: https://launch.micronaut.io/select-options
