### ISSUE TITLE
Snapshot deploys to Google Cloud is failing

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-starter#371]
```
ERROR: (gcloud.alpha.functions.deploy) OperationError: code=7, message=Build Failed: Cloud Build API has not been used in project 626602103021 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudbuild.googleapis.com/overview?project=626602103021 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

See https://github.com/micronaut-projects/micronaut-starter/runs/941097338?check_suite_focus=true#step:5:52

@jameskleeh do you have the credentials to approve this again?

**Comment by jameskleeh** [comment]
@ilopmar I just enabled it

**Comment by ilopmar** [comment]
Thanks. I'll wait for CI to finish, then I'll merge another PR into master and check if everything works properly before closing this.

**Comment by ilopmar** [comment]
@jameskleeh It has failed again https://github.com/micronaut-projects/micronaut-starter/runs/941201562?check_suite_focus=true#step:5:52

**Comment by jameskleeh** [comment]
@ilopmar I don't know of anything else to do. I would try running the build again

**Comment by ilopmar** [comment]
I've merged another PR and the deploy task failed again with the same error message :man_shrugging:
