### ISSUE TITLE
Push to Github ability

### ISSUE THREAD

**Issue by glaforge** [micronaut-projects/micronaut-starter#378]
Micronaut Launch has a preview and a generate button, but it would be nice to have another kind of button: `Push to Github`.
When clicking on the push to Github button, it would allow the user to sign in with Github, select a repository to which to push the generated project.

**Comment by graemerocher** [comment]
@glaforge Push to Github functionality would require disk access to write the project to disk before pushing it to Github. Does Cloud Run support this kind of disk access? Probably not I imagine?

**Comment by glaforge** [comment]
Yes, you can write to `/tmp` (the rest of the file system is read-only), however please note that it's a kind of RAM-disk, so it consumes the memory you allocated for the Cloud Run instance.

**Comment by graemerocher** [comment]
Shouldn't be a problem, since the zip file is only 500kb or so

**Comment by graemerocher** [comment]
@pgressa can you take this on next

**Comment by pgressa** [comment]
sure! on it

**Comment by alvarosanchez** [comment]
Is this not done already by #495?
