### ISSUE TITLE
Problem With "empty" application.yml

### ISSUE THREAD

**Issue by jeffbrown** [micronaut-projects/micronaut-starter#384]
Under certain circumstances the starter creates an `application.yml` file that is empty except for opening and closing curly braces.

```
~ $ mn create-app someapp -f config-consul
| Application created at /Users/jeffscottbrown/someapp
~ $ 
~ $ cat someapp/src/main/resources/application.yml 
{
  }
~ $
```

The same thing happens in Launch when creating a project with the `config-consul` feature (probably others, but I have not verified).

<img width="974" alt="Screen Shot 2020-08-12 at 11 13 59 AM" src="https://user-images.githubusercontent.com/15482/90041621-2c4e8980-dc8f-11ea-86de-95ba5e9a6e6d.png">

### Environment Information

- **Operating System**: macOs locally, also happens with launch.micronaut.io
- **Micronaut Version:** 2.0.1

**Comment by sdelamo** [comment]
We should probably not generate an `application.yml` in those cases.
