### ISSUE TITLE
Micronaut CLI Project Generation  GCP Function Graalvm

### ISSUE THREAD

**Issue by cassadyj** [micronaut-projects/micronaut-starter#391]
### Description

When generating a project with the google-cloud-function feature, you can also include the graalvm feature.

`mn create-app my-app -f google-cloud-function -f graalvm`

The generated project compiles and will work just fine as a GCP HTTP Function, but the docker-build process will fail when attempting to build a native image.

The project does not contain any class with a main method, as expected for serverless functions.  If one wants to generate a graal native image they would need to create a project that does not use `google-cloud-function`.

Recommend to not allow the `google-cloud-function` feature along with the `graalvm` feature.

### Steps to Reproduce

1. `mn create-app my-app -f google-cloud-function -f graalvm`
2. `./gradlew assemble`
3. `./docker-build.sh`

### Expected Behaviour

Project should not contain the ability to create a docker container with a function project

### Actual Behaviour

Docker build fails
`Error: Main entry point class 'my.app.Application' not found.
`
### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 2.0.1
- **JDK Version:** 11

**Comment by cassadyj** [comment]
Discussion:

Should the starter throw an error when these two features are selected, and recommend to the user to use a new feature "google-cloud-run" with graalvm?

OR

Should the starter understand what the user is trying to accomplish, and generate a project that can be built into a container and deployed on Cloud Run?

**Comment by graemerocher** [comment]
yes the best would be an error with recommendation. There is no way to get native functions working with GCP function

**Comment by ilopmar** [comment]
I agree with @graemerocher. This way we don't decide for the user but we provide a recommendation on how to proceed.
