### ISSUE TITLE
Generated gradle build fails with 'Plugin with id 'build-announcements' not found.'

### ISSUE THREAD

**Issue by gregopet** [micronaut-projects/micronaut-starter#435]
### Description

When trying to run any gradle task, the error `Plugin with id 'build-announcements' not found.` is returned. That plugin was removed in Gradle 6.0 (however using an older version of Gradle does not work with the included version of the Shadow plugin).

I did not provide a stacktrace because it would just be ballast - build-announcements being removed is well documented.

### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. create a micronaut application, v 2.0.1, language Kotlin, Gradle & Spock
2. unpack the downloaded zip file
3. run `gradlew compileKotlin` (or any other task)

### Expected Behaviour

Gradle task should be executed

### Actual Behaviour

Error is returned: `Plugin with id 'build-announcements' not found.`

### Environment Information

- **Operating System**: Arch Linux
- **Micronaut Version:** 2.0.1
- **JDK Version:** 13.0.1.j9-adpt

**Comment by jameskleeh** [comment]
I can't reproduce this

```
sample-projects $ mn -V
Micronaut Version: 2.0.2
sample-projects $ java -version
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7)
OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)
sample-projects $ mn create-app issue435 -l kotlin -t spock --java-version 14
| Application created at /Users/jameskleeh/IdeaProjects/sample-projects/issue435
sample-projects $ cd issue435
issue435 $ ./gradlew compileKotlin
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.5.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Task :kaptKotlin
warning: Supported source version 'RELEASE_11' from annotation processor 'org.jetbrains.kotlin.kapt3.base.ProcessorWrapper' leBUILD SUCCESSFUL in 9s
3 actionable tasks: 3 executed
issue435 $ 

```
