### ISSUE TITLE
Launch Instructions Not working

### ISSUE THREAD

**Issue by jeffbrown** [micronaut-projects/micronaut-starter#437]
The Micronaut user guide includes the following:

> Run curl https://launch.micronaut.io for more instructions on how to use the API

That does not appear to work currently.

I have not debugged to confirm that this is relevant but I wonder if the no-op method at https://github.com/micronaut-projects/micronaut-starter/blob/5c54c5e602a60d7346f3b2701b1ed51a98185a48/starter-api/src/main/java/io/micronaut/starter/api/ApplicationController.java#L112-L114 is being called.

**Comment by graemerocher** [comment]
yes I noticed this was broken as well

**Comment by jameskleeh** [comment]
This is due to https://github.com/micronaut-projects/micronaut-core/issues/4100
