### ISSUE TITLE
Explain the CLI-generated Gradle build file

### ISSUE THREAD

**Issue by martinanderssondotcom** [micronaut-projects/micronaut-starter#452]
I can not find the CLI-generated Gradle build file documented anywhere. It's not just missing from Micronaut's documentation, but to this date I can not find this file commented anywhere on the Internet.

I am specifically talking about the build file generated using the command `mn create-app hello-world` (sourced from [the userguide](https://docs.micronaut.io/snapshot/guide/index.html#creatingServer)).

In order to understand any application I always first go to the build file. In this case, I just created the most "simple" Hello World project from the official documentation. Should I assume that the generated build file is the smallest one required to get a single-line Micronaut controller up and running? I greatly suspect the file can be made much smaller and that my generated file contains plugins/dependencies/JVM arguments that are not necessary for this example project.

I will have to resort to commenting out lines in order to probe what can be left out versus what will cause my application to stop working. If I at all want to have a shoot at understanding what each one of these lines do I will have to spend my weekend googling every one of them! And I am not hopeful to be honest that I will actually manage to figure out the entire build file.

It would be great and a super helpful introduction to the entire framework if we could get this file documented!

Note: I think that long-term we should try to get this generated file reduced. But I guess we can file that as a new issue as step two in this process.

**Comment by aadrian** [comment]
The different features already have a short help with them that are also presented in the Micronaut Launch UI. 

> however its a maintenance issue because we have no system in place to ensure what is documented is what is generated. 

The `build.gradle` template could include the selected "feature description" as comments too. This way would be self-documented and always current.

This might be even an option ("Include feature description in `build.gradle` as comments") in the Launch UI and in the CLI - if some users would not like to have the `build.gradle` with comments.

**Comment by jameskleeh** [comment]
@aadrian Right - I moved this issue here because this is much more feasible with the new launch code

**Comment by graemerocher** [comment]
@martinanderssondotcom FWIW things have evolved and the shortest Gradle build file possible now is:

```groovy
plugins {
     id 'io.micronaut.application' version '{version}'
}
version "0.1"
group "com.example"

repositories {
    jcenter()
    mavenCentral()
}

micronaut {
    version = "2.0.1"
    runtime "netty"
}

dependencies {
    runtimeOnly("ch.qos.logback:logback-classic")
}

mainClassName = "example.Application"
```

**Comment by martinanderssondotcom** [comment]
Super, thank you!

Is this documented anywhere? For example, what values can I set as "runtime"?

**Comment by graemerocher** [comment]
@martinanderssondotcom we are still working on better documentation, but the list is documented here https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/master/README.md
