### ISSUE TITLE
Generation of Kotlintest projects is broken

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-starter#467]
It is not possible to Generate/Preview/Diff a project that uses Kotlintest. It doesn't matter the language or the build tool. The error is 
`Internal Server Error: Resource not found for path: src/test/kotlin/io/kotest/provided/ProjectConfig.kt`

It also happens for 2.0.2 and 2.1.0.BUILD-SNAPSHOT

![image](https://user-images.githubusercontent.com/559192/93458752-0301c880-f8e1-11ea-8a21-6db5fd56b3e3.png)

**Comment by graemerocher** [comment]
I thought kotlin test was replaced by kotest?

**Comment by ilopmar** [comment]
As we only have one common UI whayt @sdelamo did was:

- map Kotlintest to Kotest internally https://github.com/micronaut-projects/micronaut-starter/pull/428
- Remove Kotlintest https://github.com/micronaut-projects/micronaut-starter/pull/418

So even if the user select Kotlintest on the UI we will generate a Kotest project.

**Comment by sdelamo** [comment]
I think the problem is that I missed the update in ` resource-config.json `

to include this file: https://github.com/micronaut-projects/micronaut-starter/blob/2.0.x/starter-core/src/main/resources/kotest/ProjectConfig.kt

**Comment by ilopmar** [comment]
Thank you @sdelamo. I'll take a look at the PR and test it with a native-image.

**Comment by hwiegard** [comment]
It looks like the issue is still present in Micronaut 2.1.0, there the same error appears.

**Comment by ilopmar** [comment]
The problem is that we merged the fix into 2.0.x branch but never merged up the changes. This is not the only fix left behind, the one that fixes the "curl" support was also missed.

I've submitted this PR with merge of the pending changes: https://github.com/micronaut-projects/micronaut-starter/pull/512
