### ISSUE TITLE
Generate a project with azure/gcp/oracle or function feature, instructions/links in README are duplicated

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#485]

**Comment by wetted** [comment]
This is a more general problem with features that extend `AbstractFunctionFeature`, and encompasses the `azure-function`, `google-cloud-function` and `oracle-function` features. 

For azure and gcp, the instructions and doc links are duplicated when the application type is "Micronaut Application", which results in auto-adding the associated `-http` feature. 

For the `oracle-function` the doc links are duplicated when the application type is "Function Application for Serverless", whereas the feature "-http" doc links are duplicated when the application type is "Micronaut Application"
