### ISSUE TITLE
Add a way to permalink to a file in preview that can be shared

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-starter#494]
It would be nice to be able to permalink to a file in preview, something like:

```
https://micronaut.io/launch#/preview/DEFAULT/demo?path=build.gradle
```

**Comment by eahrold** [comment]
Moving over to Starter UI board https://github.com/micronaut-projects/micronaut-starter-ui/issues/8

see https://github.com/micronaut-projects/micronaut-starter-ui/issues/8#issuecomment-774741015
