### ISSUE TITLE
Switch to Jakarta Annotations API

### ISSUE THREAD

**Issue by donbeave** [micronaut-projects/micronaut-starter#497]
The current version of Micronaut Starter is generating `build.gradle` with JavaX annotations:

```kotlin
    implementation("javax.annotation:javax.annotation-api")
```

This one seems to be deprecated and replaced by the Jakarta project, maybe it's time to update it to:

```kotlin
    implementation("jakarta.annotation:jakarta.annotation-api")
```

API is the same: https://eclipse-ee4j.github.io/common-annotations-api/apidocs/

Seems it's not breaking changes dependency.

**Comment by ilopmar** [comment]
Closed by #578
