### ISSUE TITLE
micronaut 2.1.0 does not work with JDK 14 but work with JDK {8,11}

### ISSUE THREAD

**Issue by chenrui333** [micronaut-projects/micronaut-starter#498]
Per https://github.com/Homebrew/homebrew-core/pull/62020, I built and installed mn in my local, but I could not have it run with JDK14, but it works with JDK 8 or 11 though.

```
$ jenv local 1.8

$ /usr/local/Cellar/micronaut/2.1.0/bin/mn create-app hello-world
| Application created at /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/hello-world

$ jenv local 11.0

$ /usr/local/Cellar/micronaut/2.1.0/bin/mn create-app hello-world
| Application created at /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/hello-world

$ jenv local 14.0

$ /usr/local/Cellar/micronaut/2.1.0/bin/mn create-app hello-world
| Error Cannot create the project because the target directory already exists

$ jenv versions
  system
  1.8
  1.8.0.252
  11.0
  11.0.6
* 14.0 (set by /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/.java-version)
  14.0.1
  openjdk64-1.8.0.252
  oracle64-11.0.6
  oracle64-14.0.1
```

**Comment by ilopmar** [comment]
JDK 14 is now deprecated since JDK 15 was released. 

https://github.com/micronaut-projects/micronaut-starter/blob/acc2d80c4bff32a123c92ddce91c6e9987bdb6f6/starter-core/src/main/java/io/micronaut/starter/options/JdkVersion.java#L34

You can still use it if you want, just create an application with JDK15 and then modify `build.gradle`:

```groovy
java {
    sourceCompatibility = JavaVersion.toVersion('15')
    targetCompatibility = JavaVersion.toVersion('15')
}
```

**Comment by bayandin** [comment]
> JDK 14 is now deprecated since JDK 15 was released.

Thanks for the explanation, it seems an error message doesn't reflect it really:
```
==> /usr/local/Cellar/micronaut/2.1.0/bin/mn create-app hello-world
Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp
| Error Unsupported JDK version: 14. Supported values are [8, 9, 10, 11, 12, 13, 14, 15]
```
It comes from:
 https://github.com/micronaut-projects/micronaut-starter/blob/acc2d80c4bff32a123c92ddce91c6e9987bdb6f6/starter-core/src/main/java/io/micronaut/starter/options/JdkVersion.java#L54

And even verified to be "incorrect":
https://github.com/micronaut-projects/micronaut-starter/blob/acc2d80c4bff32a123c92ddce91c6e9987bdb6f6/starter-core/src/test/groovy/io/micronaut/starter/options/JdkVersionSpec.groovy#L16

**Comment by ilopmar** [comment]
@bayandin I've sent this PR to improve the error message: https://github.com/micronaut-projects/micronaut-starter/pull/505
