### ISSUE TITLE
Don't include jcenter as a repository

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#552]

**Comment by alvarosanchez** [comment]
Are we sure that, as of today, all of our dependencies are in Maven Central?

**Comment by ilopmar** [comment]
No, not all of them. At least Neo4j is missing https://github.com/micronaut-projects/micronaut-neo4j/issues/75, and probably a few more that we don't know.

**Comment by alvarosanchez** [comment]
I wasn't referring to our dependencies, but third-party's. If even not all our modules are in Central, then I would keep jcenter.

**Comment by alvarosanchez** [comment]
I think this issue should be closed. Thoughts?
