### ISSUE TITLE
Launcher for 2.2.0 generates Kotlin DSL builds with build.gradle instead of build.gradle.kts

### ISSUE THREAD

**Issue by rocketraman** [micronaut-projects/micronaut-starter#571]
Follow-up to https://github.com/micronaut-projects/micronaut-starter/pull/491, I noticed the launcher for 2.2.0.BUILD-SNAPSHOT at https://micronaut.io/launch/ outputs a gradle build using Kotlin DSL, *but* the filename is incorrectly output as `build.gradle` vs the desired `build.gradle.kts`:

![image](https://user-images.githubusercontent.com/53049/99708608-0d207e80-2a6c-11eb-9cbd-a260764e707f.png)

The downloaded file also has the incorrect file name.

**Comment by jameskleeh** [comment]
@rocketraman What makes you think its the Kotlin DSL?

**Comment by rocketraman** [comment]
The content of the file is valid Kotlin DSL.

**Comment by jameskleeh** [comment]
@rocketraman That may be the case but it looks to be valid Groovy DSL to me as well

**Comment by jameskleeh** [comment]
I don't believe this is valid in the Kotlin DSL `maven { url "https://oss.jfrog.org/oss-snapshot-local" }`

**Comment by rocketraman** [comment]
@jameskleeh Hmm, you're right, it looks like the changes from the previous version, and the merging of https://github.com/micronaut-projects/micronaut-starter/pull/491 made me think it was valid Kotlin DSL, but it isn't. Its a lot closer than the previous version, but still not complete.

With https://github.com/micronaut-projects/micronaut-starter/pull/491 merged, shouldn't choosing a Kotlin project cause a build.gradle.kts to be generated? Or is that not hooked up to the launcher code yet?

**Comment by jameskleeh** [comment]
It's not part of the launcher UI yet. It will be with the release of 2.2
