### ISSUE TITLE
micronaut.io/launch to be able to verify list of incompatible technologies

### ISSUE THREAD

**Issue by MartinBalin** [micronaut-projects/micronaut-starter#595]
Micronaut VSCode extension uses the command palette wizard to allow user select various technologies which are then used in project file and returned from micronaut.io/launch service at the end of wizard when project on backend is being generated.

For IDEs like VSCode it will be good to be able to verify the set of technologies before the end, ideally when user clicks OK in this particular wizard step. Then show error, return back in wizard and try again.

**Comment by ilopmar** [comment]
There is no specific endpoint to do that but you can use the `/diff` or `/preview` endpoints for that.

For example, if you select two incompatible features like `jdbc-tomcat` and `jdbc-hikari` and try to preview/diff the changes you will get a 400 and an error message:

```
$ curl -s https://launch.micronaut.io/preview/default/com.example.demo\?lang\=JAVA\&build\=GRADLE\&test\=JUNIT\&javaVersion\=JDK_11\&features\=jdbc-hikari\&features\=jdbc-tomcat | jq
{
  "message": "There can only be one of the following features selected: [jdbc-hikari, jdbc-tomcat]",
  "_links": {
    "self": {
      "href": "/preview/default/com.example.demo?lang=JAVA&build=GRADLE&test=JUNIT&javaVersion=JDK_11&features=jdbc-hikari&features=jdbc-tomcat",
      "templated": false
    }
  }
}
```

**Comment by graemerocher** [comment]
`/preview` seems the most appropriate yes
