### ISSUE TITLE
Generated rabbitmq maven project fails to startup context.

### ISSUE THREAD

**Issue by wetted** [micronaut-projects/micronaut-starter#599]
When generating a java, groovy, kotlin project with the rabbitmq feature for a maven build, the included test fails when the application context fails to start, with the message:

```
13:17:52.573 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [test]

io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [application] of class: com.objectcomputing.RabbitmqmvnSpec

Message: No bean of type [io.micronaut.runtime.EmbeddedApplication] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: RabbitmqmvnSpec.setApplication([EmbeddedApplication application])

	at io.micronaut.context.AbstractBeanDefinition.getBeanForMethodArgument(AbstractBeanDefinition.java:1653)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForMethodArgument(AbstractBeanDefinition.java:877)
	at io.micronaut.context.AbstractBeanDefinition.inject(AbstractBeanDefinition.java:339)
       more...
```

A further consequence is that the `CreateMessagingSpec` fails in `:test-core` causing CI failures.

Projects generated with gradle builds do not exhibit this failure, so I suspect it might be a dependency or configuration mismatch.

**Comment by wetted** [comment]
> Might be related - I noticed the same failure in CI for this PR: #598

Yes, until fixed any PR on starter will fail for this reason when `CreateMessagingSpec` fails for java/maven, groovy/maven and kotlin/mavin. I'll fix it on Monday. So far I don't see anything that makes it obvious.

**Comment by wetted** [comment]
I get this warning when building with maven, so that appears to be the problem.
```
[WARNING] The POM for io.micronaut.rabbitmq:micronaut-rabbitmq:jar:2.2.1 is invalid, transitive dependencies (if any) will not be available: 2 problems were encountered while building the effective model for io.micronaut.rabbitmq:micronaut-rabbitmq:2.2.1
[ERROR] 'dependencies.dependency.version' for io.micronaut:micronaut-messaging:jar is missing. @ 
[ERROR] 'dependencies.dependency.version' for io.micronaut:micronaut-inject:jar is missing. @ 
```

**Comment by wetted** [comment]
The difference from before (when this worked) is that building the micronaut-rabbitmq module generates a POM that is missing the dependencyManagement element.
```  
<dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.micronaut</groupId>
        <artifactId>micronaut-bom</artifactId>
        <version>2.1.4</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```
It's a change with `io.micronaut.build:micronaut-gradle-plugins` The problem started with version 2.0.12 (and is also broken in the latest 2.0.14-SNAPSHOT version). As a result the published POM for the `micronaut-rabbitmq` module is not valid. If I generate a starter project with a dependency on that module (i.e. rabbitmq feature), the effective POM that IntelliJ IDEA' maven tool generates seems correct and valid, with versions on the `micronaut-messaging` and `micronaut-inject` dependencies, but mvn is not resolving those dependencies when it needs to.

**Comment by alvarosanchez** [comment]
2.0.14, which reverts https://github.com/micronaut-projects/micronaut-build/pull/77, has been released.

**Comment by ilopmar** [comment]
I'll close this issue once micronaut-rabbitmq 2.2.2 and 2.3.1 (with the fix) are merged in core's BOM.
