### ISSUE TITLE
Cloud tests intermittent failure

### ISSUE THREAD

**Issue by jameskleeh** [micronaut-projects/micronaut-starter#631]
https://github.com/micronaut-projects/micronaut-starter/pull/630/checks?check_run_id=1749719222#step:5:229

**Comment by jameskleeh** [comment]
Same issue but different test https://github.com/micronaut-projects/micronaut-starter/runs/1763630972?check_suite_focus=true#step:5:325

**Comment by wetted** [comment]
Another intermittent failure. Not cloud, but due to a connection reset on `test basic create-messaging-app for mqttv3 and groovy and maven`

https://github.com/micronaut-projects/micronaut-starter/runs/1764182480

**Comment by alvarosanchez** [comment]
@jameskleeh aren't those issues caused by `SockekUtils.findAvailableTcpPort()`
