### ISSUE TITLE
views-pebble support

### ISSUE THREAD

**Issue by ecmel** [micronaut-projects/micronaut-starter#639]
Micronaut 2.3.1 includes support for views-pebble but cli does not support it yet.

```
implementation("io.micronaut.views:micronaut-views-pebble")
```

**Comment by ilopmar** [comment]
@ecmel This is an easy one. PRs welcome :)

**Comment by ecmel** [comment]
Added https://github.com/micronaut-projects/micronaut-starter/pull/641
