### ISSUE TITLE
Rename Oracle Cloud Features

### ISSUE THREAD

**Issue by jeffscottbrown** [micronaut-projects/micronaut-starter#681]
`github-workflow-oracle-oci-functions` and `github-workflow-oracle-oci-functions` should be renamed to `github-workflow-oracle-cloud-functions` and `github-workflow-oracle-cloud-functions`.

**Comment by jeffscottbrown** [comment]
Part of the issue is the term "oci" creates confusion in this context.

I have spoken with @graemerocher and @jameskleeh and they concur with the renaming proposal.

**Comment by jeffscottbrown** [comment]
@sdelamo @graemerocher Do you think the current feature `oci-devops-build-ci` should also be renamed?

**Comment by sdelamo** [comment]
renamed to what?

**Comment by jeffscottbrown** [comment]
> renamed to what?

I am asking if you think they should be renamed.  I am asking because I wonder if you think they should be renamed for the same reasons the `github-workflow-oracle-oci-functions` and `github-workflow-oracle-oci-functions` were renamed.  I am not asking if you think they should be renamed to anything in particular.  If you are looking for suggestions, something like `oracle-cloud-devops-build-ci` seems like a good option.

**Comment by sdelamo** [comment]
@wetted please: 

- [x]  rename the feature `oci-devops-build-ci` to  `oracle-cloud-devops-build-ci`
- [x] remove the preview flag
