### ISSUE TITLE
Inconsistent Kotlin version is used for new projects

### ISSUE THREAD

**Issue by jreznot** [micronaut-projects/micronaut-starter#699]
### Description

Inconsistent Kotlin version is used for stdlib and kotlin Gradle plugins in new projects created from https://launch.micronaut.io/.

### Task List

- [X] Steps to reproduce provided
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Go to https://launch.micronaut.io/
2. Select Kotlin language and Gradle build system
3. Generate and open project

### Expected Behaviour

Kotlin version should be the same for `kotlin-stdlib-jdk8` and Kotlin Gradle plugins.

### Actual Behaviour

build.gradle:
```
plugins {
    id("org.jetbrains.kotlin.jvm") version "1.4.10"
    id("org.jetbrains.kotlin.kapt") version "1.4.10"
}
...

dependencies {
    implementation("io.micronaut:micronaut-validation")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}")
```

gradle.properties:
```
kotlinVersion=1.4.30
```

IntelliJ IDEA highlights this:

![image](https://user-images.githubusercontent.com/1066152/111144815-a124d180-8598-11eb-9fc5-e001a073621c.png)

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 2.4.0
- **JDK Version:** 11

**Comment by graemerocher** [comment]
Yeah Kotlin version should always be pulled from the BOM

Thanks for the report

**Comment by jreznot** [comment]
By the way, Kotlin 1.4+ in Gradle adds stdlib dependency automatically. May be it makes sense to skip this line at all.
