### ISSUE TITLE
Slow CLI after 2.4.x release (Linux)

### ISSUE THREAD

**Issue by botcoder** [micronaut-projects/micronaut-starter#707]
### Description

After upgrading micronaut-cli, it takes about 8 seconds just to start up.

### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

Run both versions on Ubuntu Linux 20.10 JDK 11.
The 2.3.4 opens instantly, but the 2.4.0 takes forever (in cli time).

### Expected Behaviour

$ time mn --version
Micronaut Version: 2.3.4

real	0m0,052s
user	0m0,033s
sys	0m0,026s

### Actual Behaviour

$ time mn-linux-amd64-v2.4.0/bin/mn --version
Micronaut Version: 2.4.0

real	0m8,137s
user	0m0,051s
sys	0m0,042s

### Environment Information

- **Operating System**: Ubuntu Linux 20.10
- **Micronaut Version:** 2.4.0
- **JDK Version:** openjdk version "11.0.10" 2021-01-19 LTS

**Comment by jameskleeh** [comment]
@ilopmar Can you reproduce?

**Comment by ilopmar** [comment]
No, for me the execution is instantaneous:

```
~$ time mn --version                           
Micronaut Version: 2.4.0
mn --version  0,01s user 0,05s system 46% cpu 0,118 total
```

**Comment by ilopmar** [comment]
@botcoder how did you install the CLI? Try with Sdkman: `sdk install micronaut 2.4.0`.

Is it possible that you are running the jvm version instead of the native image?

**Comment by botcoder** [comment]
I tried using Sdkman and it doesn't have the issue, it is instant.

The version I was using is the one in the sample, available as a github release: mn-linux-amd64-v2.4.0 (https://github.com/micronaut-projects/micronaut-starter/releases/tag/v2.4.0)

**Comment by ilopmar** [comment]
I've also tried that version on Linux and it works fast for me.

**Comment by botcoder** [comment]
Please, try it on Linux without any connection, I tried in on another computer and the problem happens too.

**Comment by botcoder** [comment]
@ilopmar Sorry to keep commenting on this closed issue, but I ran strace and figured it out: it's a duplicate of https://github.com/micronaut-projects/micronaut-core/issues/1552: the CLI tries to call GCP: metadata.google.internal

I couldn't find it on the diff from 2.3.4, but that's the root cause of the issue, this URL is invalid in Ubuntu and Arch also.

**Comment by jameskleeh** [comment]
@botcoder I think the "after 2.4.0 release" was a bit of a red herring. This issue would have existed ever since we released this new CLI. I'm not aware of a reason why we need environment deduction so I've submitted a PR to turn it off for the CLI. https://github.com/micronaut-projects/micronaut-starter/pull/710
