### ISSUE TITLE
Allow for adding Gradle / Maven Plugins with starter features

### ISSUE THREAD

**Issue by JasonTypesCodes** [micronaut-projects/micronaut-starter#713]
Features in starter should have the ability to configure Gradle or Maven plugins to the build. 

In addition to adding plugin dependencies, it should also allow for adding specific configuration for the plugins to the build.gradle or pom.xml

**Comment by JasonTypesCodes** [comment]
We need this capability to complete our micronaut guide migration

**Comment by sdelamo** [comment]
Starter 2.5.x will include this.
