### ISSUE TITLE
Just got Micronauts log when I tried to submit my Chocolatey package

### ISSUE THREAD

**Issue by devedse** [micronaut-projects/micronaut-starter#756]
### Description

I just submitted a new package version for my own application to Chocolatey. This failed though so I tried checking the log file.
When I did that however I got a mixed up log file for my own tool and Micronaut:
https://gist.github.com/choco-bot/28c9f8ed04b2a66eee120a7fb5554a6a

I'm getting the feeling that they are screwing some things up over at Chocolatey 😄.

Anyway I thought I'd let you guys know as well to save you some time investigating what's going on.

### Task List

N/A

### Steps to Reproduce

N/A

### Expected Behaviour

N/A

### Actual Behaviour

N/A

### Environment Information

N/A

### Example Application

N/A

**Comment by graemerocher** [comment]
hmm, I'm not sure what we can do about this on our end. We are just using the API chocolatey provides to push the package 🤷‍♂️ https://github.com/micronaut-projects/micronaut-starter/blob/2.4.x/.github/workflows/release.yml#L400-L406

**Comment by devedse** [comment]
Yeah it's definitely not for you guys to fix, but I saw that the latest version of your package push also failed. Without any logs included.

So I just posted the logs that you should've gotten :).

**Comment by graemerocher** [comment]
Thanks for that!

**Comment by graemerocher** [comment]
It is weird since the build passed https://github.com/micronaut-projects/micronaut-starter/runs/2452020154?check_suite_focus=true#step:6:11

**Comment by devedse** [comment]
The validation happens after you submit the package (takes a few hours) so that's why your build succeeded.
If you look at chocolatey you'll see that the latest version did fail though:

https://community.chocolatey.org/packages/micronaut/2.4.4

![image](https://user-images.githubusercontent.com/2350015/116374947-137f0780-a80f-11eb-973e-815ae63d8686.png)

If you open the log file for that package you'll end up here:
https://gist.github.com/choco-bot/9326fbc94e26eb78511134218c326a5e

**Comment by graemerocher** [comment]
Gotcha. Thanks for the pointers

**Comment by devedse** [comment]
@graemerocher , you might want to resubmit your package for verification tests. I just saw that mine were now approved so it seems like the chocolatey bug was fixed.

**Comment by graemerocher** [comment]
Ok. thanks!

**Comment by graemerocher** [comment]
A newer release went out that passed the checks so it does indeed some to have been fixed. See https://community.chocolatey.org/packages/micronaut/2.5.0
