### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by migangqui** [micronaut-projects/micronaut-starter#79]
# Description

When I try to call API from ReactJS fronted, I get CORS error.

### Steps to Reproduce

1. Call API REST from Frontend.
2. Open nav console.
3. Look up "... has been blocked by CORS policy" error.

### Expected Behaviour

Return API call response.

### Actual Behaviour

CORS error.

**Comment by graemerocher** [comment]
I added the CORs config https://github.com/micronaut-projects/micronaut-starter/commit/14e169a4d814832348520d5b2d90697fb94c54dd

However you can test out locally by running `./gradlew starter-web-netty:run`
