### ISSUE TITLE
Add analytics for users created applications

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-starter#81]
It would be great to store some analytics of the apps that users create and been able to get some stats in the future:
- Java version
- Gradle/Maven
- Language
- Features most used
- ...

As we plan to deploy this to lambda/cloud functions a DB is probably not the best idea, but we should send a POST request when an application is created to somewhere and store that information.

**Comment by graemerocher** [comment]
A bean that can be written that listens for `ApplicationGeneratingEvent` event to implement this now

**Comment by graemerocher** [comment]
Implemented by `starter-analytics-postgres` subproject

**Comment by ilopmar** [comment]
Is the new app deployed somewhere?
