### ISSUE TITLE
Sort versions and features alphabetically

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-starter#89]
Sort alphabetically versions in https://micronaut-starter-staging-h2gn7na5bq-uc.a.run.app/versions
and features in  https://micronaut-starter-staging-h2gn7na5bq-uc.a.run.app/application-types/DEFAULT/features

**Comment by sdelamo** [comment]
We have these classes https://github.com/micronaut-projects/static-website/blob/master/core/src/main/groovy/io/micronaut/SoftwareVersion.groovy
