### ISSUE TITLE
launch.micronaut.io/micronaut.io/launch is broken

### ISSUE THREAD

**Issue by swaechter** [micronaut-projects/micronaut-starter#892]
### Description

At the moment I can't create a new project via https://micronaut.io/launch. Several drop down menus are empty/can't be selected and several endpoints can't be reached. It's not possible to generate a project.

### Steps to Reproduce

1. Go to https://micronaut.io/launch
2. Try to click in the application type (Empty dropdown)

### Expected Behaviour

Generate an application.

### Actual Behaviour

Several drop down menu's and information can't be displayed (See screenshot). In addition https://launch.micronaut.io/ doesn't work anymore.

![Micronaut](https://user-images.githubusercontent.com/5626755/130368634-f5bb9dfd-c9bc-4aa3-bd87-d05d21186eff.png)

I tried to clear browser caches + tried to access the page via system/mobile phones that never ever accessed the launch site: Same problem.

### Environment Information

Chrome and Edge. Location is Switzerland.

**Comment by eahrold** [comment]
@swaechter thanks for the report. Looks like there's some dns issues happening under the hood, which need to be sorted, but we could certainly handle this condition more gracefully and present a better error message.

I've made a separate issue for that https://github.com/micronaut-projects/micronaut-starter-ui/issues/60

**Comment by swaechter** [comment]
@eahrold Thanks for fixing it (James confirmed it in Gitter).
