### ISSUE TITLE
Add feature(s) for swagger-ui

### ISSUE THREAD

**Issue by opticyclic** [micronaut-projects/micronaut-starter#897]
https://micronaut.io/launch doesn't create a swagger-ui view when selecting the OpenAPI option

The docs say you can enable the view with a `openapi.properties` file containing `swagger-ui.enabled=true`
https://micronaut-projects.github.io/micronaut-openapi/latest/guide/index.html#viewsGenerationWithPropertiesFile
https://micronaut-projects.github.io/micronaut-openapi/latest/guide/index.html#propertiesFileConfiguration

However, adding this to the generated project doesn't create a view at http://localhost:8080/swagger-ui/

Ideally the generated project should contain this since I'd expect people adding OpenAPI to their starter project would like a view to check it is working.

Adding a comment in the generated `openapi.properties` file or the README explaining how to enable/disable it would work for the people that want to see it and also for the people who don't.

If it can't be added it to the generator it would be useful to link to a working example from the docs.

**Comment by ilopmar** [comment]
Those are two different things, one is create the swagger-ui automatically (or redoc or rapidoc) and another thing is exposing it.

If you take a look at the docs you linked: https://micronaut-projects.github.io/micronaut-openapi/latest/guide/index.html#swaggerui

![image](https://user-images.githubusercontent.com/559192/132226582-8dfd85dd-0836-44b1-a0c2-d5542e1d05b5.png)

**Comment by ilopmar** [comment]
So, for me this works as expected. Another different thing would be to add new features to Launch to configure automatically `swagger-ui`, `rapidoc` and `redoc` views to expose the generated views automatically (also taking security into account)

**Comment by pgressa** [comment]
Nemanja Mikic works on this stuff here, but he can't assign the issue yet

**Comment by altro3** [comment]
@sdelamo as I see, it's already done
