### ISSUE TITLE
Don't Generate Package Local Classes

### ISSUE THREAD

**Issue by opticyclic** [micronaut-projects/micronaut-starter#898]
The launcher generates multiple package local classes in a single file.
e.g.

    @Controller("/demo")
    public class DemoController {
    
        @Produces(MediaType.TEXT_PLAIN)
        @Get
        public String index() {
            return "Example Response";
        }
    
        @Post
        public SampleReturnMessage postMethod(@Body SampleInputMessage inputMessage){
          SampleReturnMessage retMessage = new SampleReturnMessage();
          retMessage.setReturnMessage("Hello " + inputMessage.getName() + ", thank you for sending the message");
          return retMessage;
        }
    }
    
    @Introspected
    class SampleInputMessage{
        private String name;
    
        public SampleInputMessage() {
        }
    
        public SampleInputMessage(String name) {
            this.name = name;
        }
    
        public String getName() {
            return name;
        }
        public void setName(String name) {
            this.name = name;
        }
    }
    
    @Introspected
    class SampleReturnMessage{
        private String returnMessage;
        public String getReturnMessage() {
            return returnMessage;
        }
        public void setReturnMessage(String returnMessage) {
            this.returnMessage = returnMessage;
        }
    }

This generally isn't recommended as it makes the code harder to read and some people would go so far as [to call it a mess](https://stackoverflow.com/a/2336739/).

On top of that, these classes are package local which isn't that useful when a lot (most?) people have controllers and models in different packages.

Generating a project with a fairly common layout is more useful as a starter project that you can build on without having to do lots of refactoring.

**Comment by ilopmar** [comment]
Can you please share which features generate that code?

**Comment by jameskleeh** [comment]
Closing this because we don't generate that code
