### ISSUE TITLE
Hibernate Validator feature

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#93]
Currently we add `micronaut-hibernate-validator` when you use `hibernate-gorm`. 

I think Hibernate validator should be its own feature. 

Maybe `hibernate-gorm` should pull that feature transitivitely. 

see [Micronaut Hibernate Validator Configuration](https://micronaut-projects.github.io/micronaut-hibernate-validator/latest/guide/index.html)

**Comment by jameskleeh** [comment]
This was already done when hibernate-gorm was introduced https://github.com/micronaut-projects/micronaut-starter/commit/c1f2c21e6df09a277be3f1ebf9de8b1a51604b14#diff-876d8495fe49c50ffcbcef71b2f80b56
