### ISSUE TITLE
Starter shows 3.1.0 twice

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#937]
<img width="552" alt="Screenshot 2021-10-12 at 09 21 43" src="https://user-images.githubusercontent.com/864788/136910217-d8a3e5ae-a597-4f16-bbe0-0def8fe855f9.png">

**Comment by sdelamo** [comment]
This is now solved

**Comment by ilopmar** [comment]
This is working now because I pushed `3.2.x` branch that was missing. The problem now is that it shows `3.2.0-SNAPSHOT` instead of `3.1.1-SNAPSHOT`

![image](https://user-images.githubusercontent.com/559192/137100789-20de5367-fddb-42de-a4b9-bfaddd9216fe.png)

**Comment by sdelamo** [comment]
@ilopmar can we document how that radio button part works? Do you know that? With the goal of generating a release checklist.

**Comment by ilopmar** [comment]
Now it shows 3.1.1-SNAPSHOT:

![image](https://user-images.githubusercontent.com/559192/137687151-b8357d71-687f-429f-ad5c-bcb85ce3a241.png)

When loading the UI it sends the following requests to fetch versions different subdomains:

- https://launch.micronaut.io/versions -> 3.1.0
- https://snapshot.micronaut.io/versions -> 3.1.1-SNAPSHOT
- https://prev.micronaut.io/versions -> 2.5.13
- https://next.micronaut.io/versions -> 404

But I don't know how it works 100% and why after I created the 3.2.x branch it showed that but then now 3.1.1-SNAPSHOT is there.

I think @eahrold (and probably @jameskleeh) know how this works.

**Comment by jameskleeh** [comment]
Because when you push it deploys to snapshot.micronaut.io currently on both 3.2.x and 3.1.x. Edit: I've fixed it so only 3.1.x does

**Comment by eahrold** [comment]
@jameskleeh this has been sitting out there for a while now, and it may be a good time to bring it in https://github.com/micronaut-projects/micronaut-starter-ui/pull/59. 

It should at least make updating / adding versions a bit cleaner in the event that you want to add multiple snapshots.

**Comment by ilopmar** [comment]
Maybe we can reuse `next.micronaut.io` for the snapshots of the next version (either minor or major)

**Comment by jameskleeh** [comment]
@ilopmar We could but it would complicate things as we would have to duplicate build files. I don't see what the problem is  with the current system. I don't anticipate ever adding another version "type"

**Comment by ilopmar** [comment]
The problem is/was the we (Sergio and I) didn't know how this worked, and that it's not documented or part of a checklist of steps to do when doing a release. That's why 3.1.0 was duplicated in the first place and that's why after I added the missing 3.2.x branch that snapshot appeared (without Sergio and me knowing why)

**Comment by jameskleeh** [comment]
I agree the UI should be documented

**Comment by sdelamo** [comment]
Has anyone created the issue for documenting the UI?
