### ISSUE TITLE
"Push to GitHub" fails when using 2FA

### ISSUE THREAD

**Issue by burtbeckwith** [micronaut-projects/micronaut-starter#999]
If the GitHub account has 2FA active, after clicking "Push to GitHub" and authorizing the OAuth request, you get the error `Failed to get user access token.`

If it's not practical to request and send a 2FA token, we should detect that 2FA is active and/or display a more informative error message.

**Comment by olyagpl** [comment]
I hit the same problem. Some additional information, I received an email notification from GitHub with the following content:

_A third-party OAuth application (Micronaut Launch) with public_repo, read:user, and workflow scopes was recently authorized to access your account.
Visit [link] for more information.

To see this and other security events for your account, visit [link]._

**Comment by pgressa** [comment]
Nemanja Mikic works on this stuff here, but he can't assign the issue yet
